# l2h-mathjax-init.pl — MathJax setup for latex2html
# Shared across JOS projects via the jos-latex submodule.
#
# Usage: In your project's dot-latex2html-init, add:
#   require "$initdir/jos-latex/l2h-mathjax-init.pl";
# where $initdir is the project root (already set in dot-latex2html-init).

use File::Basename;
use Cwd qw(abs_path);
my $_jl_dir = dirname(abs_path(__FILE__));

$USE_MATHJAX = 1;
$MATHJAX_EXTERNAL_CONFIG = 1;  # write shared mathjax-config.js; browser caches it across pages
require "$_jl_dir/mathjax-macros.pl";

# \fbox{X}: render as a CSS-bordered inline-block in HTML, leaving the
# content X to be processed by latex2html's normal pipeline (so embedded
# \begin{tabular}, math, etc. are handled correctly).  Without this
# handler, latex2html's MathJax pipeline wraps \fbox{...} in \(...\),
# which fails when the contents include text-mode constructs that
# MathJax cannot parse (e.g. \begin{tabular}).  PDF rendering is
# unaffected since this hook is only consulted by latex2html.
#
# Defined here (not in mathjax-macros.pl) because mathjax-macros.pl is
# auto-regenerated by tools/generate_mathjax_macros.py, which would
# strip a hand-edited do_cmd_fbox on the next regen and silently
# reintroduce the \fbox{\begin{tabular}...} MathJax-math-mode bug.
sub do_cmd_fbox {
    local($_) = @_;
    my $arg = '';
    s/$next_pair_pr_rx/$arg = $2;''/eo
        || s/$next_pair_rx/$arg = $2;''/eo
        || ($arg = &missing_braces);
    return qq{<span class="fbox" style="border:1px solid; padding:0.25em 0.5em; display:inline-block">$arg</span>} . $_;
}

# Undo l2hconf.pm's image-mode registration of text-mode commands that
# have native do_cmd_* handlers in mathjax-macros.pl.  l2hconf.pm is
# loaded by `use l2hconf` very early in latex2html -- well before this
# init file -- and registers e.g. \fbox via process_commands_in_tex,
# creating a wrap_cmd_fbox that latex2html's wrap_raw_arg_cmds then
# dispatches to in preference to do_cmd_fbox.  That wraps \fbox{...}
# in a tex2html_wrap environment, which (in MathJax mode) emerges as
# `\(\fbox{...}\)` and fails when the contents include text-mode
# constructs MathJax cannot parse (\begin{tabular}, etc).  Removing
# wrap_cmd_fbox and the raw_arg_cmds entry lets \fbox fall through to
# normal translate_commands dispatch and reach do_cmd_fbox.
for my $cmd ('fbox') {
    next unless (defined &{"main::do_cmd_$cmd"});
    undef &{"main::wrap_cmd_$cmd"} if (defined &{"main::wrap_cmd_$cmd"});
    delete $main::raw_arg_cmds{$cmd};
}

# Expand environment-abbreviation macros from stddefs.tex before
# latex2html's environment parser runs (fixes long-standing l2h issue
# noted in stddefs.tex line 143: "l2h gets fouled up on \BIT").
# Uses the pre_pre_process hook called at the top of pre_process().
# pre_process is also called on the .aux file, so we use this same hook
# to strip "on page \pageref{...}" tails (see comment below).
sub pre_pre_process {
    s/\\BIT\b/\\begin{itemize}/g;
    s/\\EIT\b/\\end{itemize}/g;
    s/\\bit\b/\\begin{itemize}/g;
    s/\\eit\b/\\end{itemize}/g;
    s/\\BNUM\b/\\begin{enumerate}/g;
    s/\\ENUM\b/\\end{enumerate}/g;
    s/\\bnum\b/\\begin{enumerate}/g;
    s/\\enum\b/\\end{enumerate}/g;
    s/\\BITC\b/\\begin{itemize}/g;
    s/\\EITC\b/\\end{itemize}/g;
    s/\\BNUMC\b/\\begin{enumerate}/g;
    s/\\ENUMC\b/\\end{enumerate}/g;

    # Strip "on page \pageref{...}" / "starting on page \pageref{...}" /
    # ", p. \pageref{...}" patterns.  stddefs.tex defines \fpref, \Fpref,
    # \Fbpref, \epref, \spref, \cpref, \cprefs, \prefp etc. all as
    #     \Xref{ref}  \latex{ on \Xpageref{ref} }
    # In a PDF build, LaTeX expands the \latex{...} part (since
    # \newcommand{\latex}[1]{#1}) and writes the full "Fig. N on page P"
    # text into .aux.  In the HTML build, latex2html's html.perl puts
    # \latex in its ignore-commands list, so the body's \fpref expands to
    # just "Fig. N" -- but the .aux still has the long form.  l2h's
    # caption-matching code sanitizes both and compares them as hash keys;
    # if the keys diverge, the figure loses its number ("Figure:" instead
    # of "Figure 2.9:").  Stripping the LaTeX-side page-ref tail here (on
    # the raw .aux line, before \pageref gets resolved) aligns the keys
    # while leaving the visible HTML output unchanged.  The body never
    # carries an "on page X" tail in this position (the \latex{...} arg is
    # discarded by l2h), so this is a no-op on the document body.
    s/\s*(?:starting\s+)?on\s+page(?:\{\}|~|\\\@|\s|\\,)\s*\\pageref\s*\{[^}]*\}//g;
    s/\s*,\s*p\.\s*(?:\\qsp|\\,)?\s*\\pageref\s*\{[^}]*\}//g;
}

# NOTE: Earlier versions of this file defined do_cmd_ccrmahomepage and
# do_cmd_josemail to render those macros for HTML output. They were
# removed because they conflict with the \newcommand definitions in
# jos-latex/styles/stddefs.tex: latex2html warns "previous meaning will
# be lost" and then renders neither the perl handler nor the \newcommand
# expansion, producing the garbled "Julius O. Smith IIIjos" on title
# pages and an empty rendering for \josemail. The stddefs.tex
# \newcommand definitions handle both PDF and HTML output on their own.

1;
