# mathjax-macros.pl — AUTO-GENERATED by generate_mathjax_macros.py
# DO NOT EDIT — regenerate with:
#   python3 /w/jos-latex/tools/generate_mathjax_macros.py
#
# 953 math macros from 6 style files

# MathJax macro definitions
%MATHJAX_MACROS = (
    'AK' => '\\Amtx_K',
    'AKt' => '\\tilde{\\Amtx}_K',
    'AKtt' => '\\Att_K',
    'AKttt' => '\\nacc{\\vdash\\!\\!\\dashv}{\\Amtx}_K',
    'AKtttt' => '\\nacc{\\rightleftharpoons}{\\Amtx}_K',
    'AP' => ['\\text{AP}_{#1}^{\\,#2}', 2],
    'AW' => '\\Amtx_W',
    'AWt' => '\\tilde{\\Amtx}_W',
    'AWtt' => '\\Att_W',
    'AWttt' => '\\nacc{\\vdash\\!\\!\\dashv}{\\Amtx}_W',
    'AWtttt' => '\\nacc{\\rightleftharpoons}{\\Amtx}_W',
    'Ab' => '\\mathbf{A}',
    'Abt' => '\\tilde{\\Ab}',
    'Acorr' => '\\oper{Acorr}',
    'Ah' => '{\\hat A}',
    'Alias' => '\\oper{Alias}',
    'Allp' => 'H_a',
    'AllpConsol' => 'H_c',
    'Alpha' => '\\Ascr',
    'Am' => 'A^\\tminus',
    'Amtx' => '\\mathbf{A}',
    'Amtxt' => '\\Amtx^\\ast',
    'Ao' => 'A',
    'Ap' => 'A^\\tplus',
    'Ascr' => '\\mathcal{A}',
    'At' => '\\tilde{A}',
    'Atilde' => '\\tilde{A}',
    'Atmtx' => '\\tilde{\\Amtx}',
    'Atmtxt' => '\\Atmtx^\\ast',
    'Att' => '\\nacc{\\vdash}{\\Amtx}',
    'BK' => '\\Bmtx_K',
    'BW' => '{\\Bmtx_W}',
    'Bb' => '\\mathbf{B}',
    'Bh' => '{\\hat B}',
    'Bmtx' => '\\mathbf{B}',
    'Bscr' => '\\mathcal{B}',
    'Bt' => '{\\tilde B}',
    'Btmtx' => '\\tilde{\\Bmtx}',
    'CK' => '\\Cmtx_K',
    'CN' => '\\complex^N',
    'CW' => '\\Cmtx_W',
    'CZeroPad' => '\\oper{CausalZeroPad}',
    'Cb' => '\\mathbf{C}',
    'Chop' => '\\oper{Chop}',
    'Cmtx' => '\\mathbf{C}',
    'Cn' => 'C(n)',
    'Conv' => '\\oper{Conv}',
    'Corr' => '\\oper{Corr}',
    'Cscr' => '\\mathcal{C}',
    'Ct' => '{\\tilde C}',
    'Ctmtx' => '\\tilde{\\Cmtx}',
    'DCT' => '\\oper{DCT}',
    'DEL' => ['z^{-#1\\Fs}', 1],
    'DFT' => '\\oper{DFT}',
    'DK' => '\\Dmtx_K',
    'DST' => '\\oper{DST}',
    'DTFT' => '\\oper{DTFT}',
    'DW' => '\\Dmtx_W',
    'Db' => '{\\mathbf D}',
    'Dec' => '\\oper{Downsample}',
    'Deltab' => '{\\boldsymbol\\Delta}',
    'Delv' => '{\\underline{\\Delta}}',
    'Dmtx' => '\\mathbf{D}',
    'Dmtxi' => '\\Dmtx^{-1}',
    'Dmtxt' => '\\Dmtx^\\ast',
    'Dmtxti' => '\\Dmtx^{-\\ast}',
    'Dscr' => '\\mathcal{D}',
    'Dt' => '{\\tilde D}',
    'Dtd' => '{\\dot D_t}',
    'Dtmtx' => '\\tilde{\\Dmtx}',
    'E' => ['\\Escr\\left\\lbrace#1\\right\\rbrace', 1],
    'EDC' => '\\text{EDC}',
    'EDR' => '\\text{EDR}',
    'Eh' => '\\hat E',
    'Em' => 'E',
    'Emi' => 'E^{-1}',
    'Emtx' => '\\mathbf{E}',
    'Emtxi' => '\\Emtx^{-1}',
    'Emtxt' => '\\Emtx^\\ast',
    'Emtxti' => '\\Emtx^{-\\ast}',
    'Energy' => '\\oper{E}',
    'Esc' => '\\text{e}',
    'Escr' => '\\mathcal{E}',
    'Ev' => ['\\mathcal{E}\\left\\lbrace#1\\right\\rbrace', 1],
    'FBCF' => ['\\text{FBCF}_{#1}^{\\,#2}', 2],
    'FFCF' => ['\\text{FFCF}_{#1}^{\\,#2}', 2],
    'FFT' => '\\oper{FFT}',
    'FT' => '\\oper{FT}',
    'Fa' => 'F_a',
    'Fb' => 'F_b',
    'Fbold' => '\\mathbf{F}',
    'Fd' => 'F_d',
    'Flip' => '\\oper{Flip}',
    'Fm' => 'F^\\tminus',
    'Fp' => 'F^\\tplus',
    'Fs' => 'f_s',
    'Fscr' => '\\mathcal{F}',
    'Fv' => '\\underline{F}',
    'G' => '\\Gamma',
    'Gb' => '\\Gmtx',
    'Geemtx' => '{\\boldsymbol G}',
    'Gh' => '{\\hat G}',
    'Gmtx' => '{\\boldsymbol \\Gamma}',
    'Gt' => '\\tilde{\\Gamma}',
    'Gtv' => '\\tilde{\\Gb}',
    'Gtvt' => '\\tilde{\\Gb}^T',
    'Gv' => '{\\Gmtx}',
    'Gvt' => '\\Gmtx^T',
    'Gz' => '\\G_0',
    'HL' => 'H_{L,\\omega_1}',
    'Hb' => 'H_b',
    'Hbold' => '\\mathbf{H}',
    'Hh' => '{\\hat H}',
    'Hha' => '\\hat{H}^\\ast',
    'Hhl' => '\\Hh_l',
    'Hhs' => '\\Hh_s',
    'Hl' => 'H_l',
    'Hmtx' => '\\mathbf{H}',
    'Hmtxt' => '{\\tilde{\\Hmtx}}',
    'Hs' => 'H_s',
    'Hscr' => '\\mathcal{H}',
    'Ht' => '\\tilde{H}',
    'Htmtx' => '{\\tilde{\\Hmtx}}',
    'Hv' => '\\underline{H}',
    'IDFT' => '\\oper{IDFT}',
    'IDTFT' => '\\oper{IDTFT}',
    'IFFT' => '\\oper{IFFT}',
    'IFT' => '\\oper{IFT}',
    'Im' => '\\text{Im}',
    'Imtx' => '\\mathbf{I}',
    'Interp' => '\\oper{Interp}',
    'Iscr' => '\\mathcal{I}',
    'Iv' => '\\underline{I}',
    'Jmtx' => '\\mathbf{J}',
    'Kmtx' => '\\mathbf{K}',
    'LBCF' => ['\\text{LBCF}_{#1}^{\\,#2,\\,#3}', 3],
    'Lamm' => '{\\boldsymbol \\Lambda}',
    'Laplace' => '\\mathcal{L}',
    'Linf' => '{L_\\infty}',
    'Lmtx' => '\\mathbf{L}',
    'Lo' => 'L',
    'Lone' => '{L_1}',
    'Lp' => '{L_p}',
    'Lscr' => '\\mathcal{L}',
    'Ltwo' => '{L_2}',
    'Ltwotext' => '\\Ltwo',
    'Lv' => '\\underline{L}',
    'M' => 'm',
    'Mh' => '\\hat{M}',
    'Mmtx' => '\\mathbf{M}',
    'Na' => 'N_\\Allp',
    'Nah' => '{\\hat{N}_a}',
    'Nb' => '{N_b}',
    'Nbh' => '{\\hat{N}_b}',
    'Nc' => '{N_c}',
    'Newtons' => '\\text{ N}',
    'Ngh' => 'N_\\gh',
    'Nh' => '{\\hat N}',
    'Nsc' => '\\text{n}',
    'Nscr' => '\\mathcal{N}',
    'Nus' => '\\nu_s',
    'Nyquist' => '\\oper{Nyquist}',
    'Op' => '\\oper{Op}',
    'Oscr' => '\\mathcal{O}',
    'PInterp' => '\\oper{PerInterp}',
    'Pb' => 'p_b',
    'Pbm' => '\\Pb^\\tminus',
    'Pbp' => '\\Pb^\\tplus',
    'Pd' => 'p_\\tdelta',
    'Pdc' => '\\Pd^c',
    'Pdp' => '\\Pd^\\tplus',
    'Pds' => '\\Pd^\\ast',
    'Pee' => 'P',
    'Ph' => '{\\hat P}',
    'Phd' => '{\\hat p}_\\tdelta',
    'Phds' => '\\Phd^\\ast',
    'Phl' => '\\Ph_l',
    'Pl' => '{P_l}',
    'Pm' => 'p_m',
    'Pms' => '\\Pee^-(s)',
    'Pmtx' => '\\mathbf{P}',
    'Pofs' => '\\Pee(s)',
    'Pomo' => 'P_1^\\tminus',
    'Popo' => 'P_1^\\tplus',
    'Ppms' => '\\Pee^\\pm(s)',
    'Pps' => '\\Pee^+(s)',
    'Ps' => '\\mathcal{P}',
    'Pscr' => '\\mathcal{P}',
    'Psm' => '\\Ps^\\tminus',
    'Psp' => '\\Ps^\\tplus',
    'Psx' => '\\Pee(s,\\x)',
    'Ptmo' => 'P_2^\\tminus',
    'Ptpo' => 'P_2^\\tplus',
    'Pu' => '\\Pmtx_{\\uv}',
    'Qmtx' => '\\mathbf{Q}',
    'R' => 'R',
    'RMM' => '\\reals^M',
    'RMS' => '\\text{RMS}',
    'RN' => '\\reals^N',
    'RR' => 'S',
    'RRt' => '\\tilde{S}',
    'Ra' => 'R_A',
    'Radius' => 'r',
    'Ram' => '\\Ra^\\tminus',
    'Rams' => '\\Ram(s)',
    'Rap' => '\\Ra^\\tplus',
    'Rapm' => '\\Ra^\\pm',
    'Rapms' => '\\Rapm(s)',
    'Raps' => '\\Rap(s)',
    'Ras' => '\\Ra(s)',
    'Rb' => 'R_b',
    'Rbh' => '\\hat R_b',
    'Rbt' => '\\tilde{R}_b',
    'Rc' => '\\R',
    'Rcm' => '\\Rc^\\tminus',
    'Rcms' => '\\Rcm(s)',
    'Rcp' => '\\Rc^\\tplus',
    'Rcpm' => '\\Rc^\\pm',
    'Rcpms' => '\\Rcpm(s)',
    'Rcps' => '\\Rcp(s)',
    'Rcs' => '\\Rc(s)',
    'Re' => '\\text{Re}',
    'RectWin' => '\\oper{Chop}',
    'Rejphi' => 'R\\,e^{j\\phi}',
    'Repeat' => '\\oper{Repeat}',
    'Rho' => '\\hat{\\rho}',
    'Rhot' => '\\hat{\\tilde{\\rho}}',
    'Ri' => '\\R_i',
    'Rimo' => '\\R_{i-1}',
    'Rm' => 'R_m',
    'Ro' => 'R_1',
    'Rp' => '\\R^\\tplus',
    'Rpm' => '\\R^\\pm',
    'Rpms' => '\\Rpm(s)',
    'Rs' => '\\R(s)',
    'Rscr' => '\\mathcal{R}',
    'Rthree' => '\\reals^3',
    'Rtube' => '\\R_{\\text{T}}',
    'Rz' => 'R_0',
    'STFT' => '\\oper{STFT}',
    'Sample' => '\\oper{Sample}',
    'Sb' => '\\Rho_b',
    'Scale' => '\\oper{Scale}',
    'Select' => '\\oper{Downsample}',
    'Shift' => '\\oper{Shift}',
    'Sinc' => '\\oper{Sinc}',
    'So' => 'S',
    'Ssc' => '\\text{s}',
    'Sscr' => '\\mathcal{S}',
    'Stretch' => '\\oper{Stretch}',
    'T' => 'K',
    'Tau' => '\\hat{\\tau}',
    'Tb' => '\\mathbf{\\T}',
    'Tbi' => '\\Tb^{-1}',
    'Tbit' => '{\\Tbi}^\\ast',
    'Tbt' => '\\Tb^\\ast',
    'Thh' => '\\hat{\\Theta}',
    'Tm' => '\\mathbf{T}',
    'Tmi' => '\\Tm^{-1}',
    'To' => 'T',
    'Ts' => 'T',
    'Tscr' => '\\mathcal{T}',
    'Tso' => '\\Ts(\\omega)',
    'U' => 'u',
    'Ub' => '\\U_b',
    'Ubm' => '\\Ub^\\tminus',
    'Ubp' => '\\Ub^\\tplus',
    'Uc' => 'U',
    'Ucms' => '\\Uc^\\tminus(s)',
    'Ucpms' => '\\Uc^\\pm(s)',
    'Ucps' => '\\Uc^\\tplus(s)',
    'Ucs' => '\\Uc(s)',
    'Um' => '\\U_m',
    'Ums' => '\\U^\\tminus(s)',
    'Umtx' => '\\mathbf{U}',
    'Umtxi' => '\\Umtx^{-1}',
    'Umtxt' => '\\Umtx^\\ast',
    'Umtxti' => '\\Umtx^{-\\ast}',
    'Upms' => '\\U^\\pm(s)',
    'Ups' => '\\U^\\tplus(s)',
    'Us' => '\\U(s)',
    'V' => 'V',
    'Va' => 'V_a',
    'Var' => ['\\text{Var}\\left\\lbrace#1\\right\\rbrace', 1],
    'Vb' => 'V_b',
    'Vd' => 'V_d',
    'Vht' => '\\hat{\\Vt}',
    'Vm' => '\\V^\\tminus',
    'Vmtx' => '\\mathbf{V}',
    'Vp' => '\\V^\\tplus',
    'Vt' => '\\dot V',
    'Vv' => '\\underline{V}',
    'Wb' => '{\\mathbf{W}}',
    'Wm' => 'W^\\tminus',
    'Wmtx' => '\\mathbf{W}',
    'Wp' => 'W^\\tplus',
    'Wsc' => '\\text{w}',
    'X' => 'X',
    'Xb' => '\\mathbf{X}',
    'Xs' => 'X',
    'Xscr' => '\\mathcal{X}',
    'Xv' => '\\underline{X}',
    'Yb' => '\\mathbf{Y}',
    'Ym' => 'Y^\\tminus',
    'Yp' => 'Y^\\tplus',
    'Yv' => '\\underline{Y}',
    'Yx' => 'Y\'',
    'ZeroPad' => '\\oper{ZeroPad}',
    'Zeromtx' => '\\mathbf{0}',
    'Zscr' => '\\mathcal{Z}',
    'Zt' => ['{\\boldsymbol{\\mathcal{Z}}\\{#1\\}}', 1],
    'ab' => '\\mathbf{a}',
    'abar' => '\\overline{a}',
    'abs' => ['\\left|#1\\right|', 1],
    'abstext' => ['|#1|', 1],
    'ah' => '{\\hat a}',
    'alias' => '\\oper{Alias}',
    'amp' => '\\mathrm{A}',
    'apm' => 'a^\\pm',
    'approaches' => '\\to',
    'approxs' => '\\,\\;\\approx\\;\\,',
    'arccosh' => '\\operatorname{arccosh}',
    'arcsinh' => '\\operatorname{arcsinh}',
    'asinc' => '\\text{asinc}',
    'at' => ['\\abstext{#1}', 1],
    'av' => '\\underline{a}',
    'avg' => '\\text{AVG}',
    'bb' => '\\mathbf{b}',
    'beev' => '\\underline{b}',
    'bh' => '{\\hat b}',
    'biglp' => '\\left(',
    'bigrp' => '\\right)',
    'bl' => '\\left(',
    'bmtx' => '{\\mathbf{b}}',
    'br' => '\\right)',
    'bt' => '\\tilde{b}',
    'bv' => '\\underline{\\beta}',
    'ceil' => ['\\left\\lceil #1\\right\\rceil', 1],
    'ceiltext' => ['\\lceil{#1}\\rceil', 1],
    'chati' => '{\\hat c}_i',
    'chis' => '{\\hat c}^2_i',
    'choosenp' => ['\\begin{array}{c}#1\\\\#2\\end{array}', 2],
    'choosep' => ['\\left(\\choosenp{#1}{#2}\\right)', 2],
    'ci' => 'R',
    'circonv' => '\\circledast',
    'cm' => '\\text{ cm}',
    'cn' => 'c_n',
    'co' => 'c(\\omega)',
    'cola' => '\\oper{Cola}',
    'complex' => '\\mathbb{C}',
    'conj' => ['\\overline{#1}', 1],
    'conv' => '\\ast',
    'corrto' => '\\;\\longleftrightarrow\\;',
    'corrtotext' => '\\;\\leftrightarrow\\;',
    'coul' => '\\text{coul}',
    'cp' => 'c',
    'cpile' => ['\\matrix{#1}', 1],
    'crg' => '\\\\',
    'crgg' => '\\\\ \\\\',
    'cscalar' => 'c',
    'cv' => '\\underline{c}',
    'cz' => 'c_0',
    'dB' => '\\text{dB}',
    'db' => '{\\mathbf d}',
    'dec' => '\\oper{Dec}',
    'degC' => '\\text{${}^{\\circ}$\\rm C}',
    'degF' => '\\text{${}^{\\circ}$\\rm F}',
    'degK' => '\\text{${}^{\\circ}$\\rm K}',
    'degrees' => '\\text{${}^{\\circ}$}',
    'del' => 'd',
    'delop' => ['z^{-#1}', 1],
    'deltab' => '{\\boldsymbol\\delta}',
    'deltav' => '\\underline{\\delta}',
    'df' => 'f_{\\tdelta}',
    'dft' => '\\oper{DFT}',
    'dftilde' => '\\tilde{\\fd}',
    'dhv' => '\\underline{dh}',
    'diag' => '\\text{diag}',
    'dinv' => 'z',
    'domega' => '{\\tdelta}\\omega',
    'don' => '\\frac{d\\omega}{2\\pi}',
    'dpb' => '\\del\\mathbf{p}',
    'dpoper' => ['\\dfrac{\\partial}{\\partial #1}', 1],
    'dqb' => '\\del\\mathbf{q}',
    'ds' => ['\\downarrow\\!\\!#1', 1],
    'dscalar' => 'd',
    'dtft' => '\\oper{DTFT}',
    'dv' => '\\underline{d}',
    'dynes' => '\\text{ dynes}',
    'e' => '\\epsilon',
    'eb' => '\\mathbf{e}',
    'eh' => '\\hat e',
    'ejo' => 'e^{j\\omega}',
    'ejoT' => 'e^{j\\omega T}',
    'ejok' => 'e^{j\\ok}',
    'ejokT' => 'e^{j\\omega_kT}',
    'ejon' => 'e^{j\\omega n}',
    'ejonT' => 'e^{j\\omega n\\Ts}',
    'emjo' => 'e^{-j\\omega}',
    'emjoT' => 'e^{-j\\omega T}',
    'emjok' => 'e^{-j\\omega_k}',
    'emjokT' => 'e^{-j\\omega_kT}',
    'emjon' => ['e^{-j\\omega #1}', 1],
    'emph' => ['\\textit{#1}', 1],
    'emtx' => '{\\mathbf{e}}',
    'ensuremath' => ['#1', 1],
    'env' => '\\oper{Envelope}',
    'eps' => '\\epsilon',
    'eqbydef' => '\\mathrel{\\stackrel{\\Delta}{=}}',
    'eqmaybe' => '\\mathrel{\\stackrel{?}{=}}',
    'eqs' => '\\,\\mathrel{\\mathop=}\\,',
    'eqsp' => '\\;=\\;',
    'eqss' => '\\,\\;=\\;\\,',
    'ergs' => '\\text{ erg}',
    'ergsns' => '\\text{erg}',
    'esa' => 'e^{s(t\\pm x/c)}',
    'esam' => 'e^{s(t-x/c)}',
    'esap' => 'e^{s(t+x/c)}',
    'esiam' => 'e^{\\si(t-x/c)}',
    'esiap' => 'e^{\\si(t+x/c)}',
    'etab' => '\\overline{\\eta}',
    'etabh' => '\\overline{\\hat \\eta}',
    'etah' => '{\\hat \\eta}',
    'etm' => 'e',
    'ev' => '\\underline{e}',
    'farad' => '\\mathrm{F}',
    'fd' => 'f_d',
    'fft' => '\\oper{FFT}',
    'fh' => '{\\hat f}',
    'fhmimo' => '\\fh^\\tminus_{i-1}',
    'fhpi' => '\\fh^\\tplus_i',
    'fhpimo' => '\\fh^\\tplus_{i-1}',
    'fivebyone' => ['\\left[\\fivebyonenp{#1}{#2}{#3}{#4}{#5}\\right]', 5],
    'fivebyonenp' => ['\\begin{array}{c} #1 \\\\[2pt] #2 \\\\[2pt] #3 \\\\[2pt] #4\\\\[2pt] #5\\end{array}', 5],
    'fivebyonens' => ['\\left[\\!\\!\\fivebyonenp{#1}{#2}{#3}{#4}{#5}\\!\\!\\right]', 5],
    'fl' => '{f_l}',
    'flip' => '\\oper{Flip}',
    'floor' => ['\\left\\lfloor #1\\right\\rfloor', 1],
    'floortext' => ['\\lfloor#1\\rfloor', 1],
    'floortextop' => '\\oper{floor}',
    'fm' => 'f^{\\tminus}',
    'fmax' => 'f_{\\text{max}}',
    'fmi' => '\\fm_i',
    'fmimo' => '\\fm_{i-1}',
    'fn' => '\\tilde{f}',
    'fnm' => '\\fn^\\tminus',
    'fnmi' => '\\fn^\\tminus_i',
    'fnmimo' => '\\fn^\\tminus_{i-1}',
    'fnp' => '\\fn^\\tplus',
    'fnpi' => '\\fn^\\tplus_i',
    'fnpimo' => '\\fn^\\tplus_{i-1}',
    'fnpm' => '\\fn^\\pm',
    'fofx' => 'f(t,\\x)',
    'foop' => 'x^\\tplus',
    'foot' => '\\mathrm{ft}',
    'fourbyone' => ['\\left[\\fourbyonenp{#1}{#2}{#3}{#4}\\right]', 4],
    'fourbyonenp' => ['\\begin{array}{c} #1 \\\\[2pt] #2 \\\\[2pt] #3 \\\\[2pt] #4\\end{array}', 4],
    'fp' => 'f^{\\tplus}',
    'fpi' => '\\fp_i',
    'fpimo' => '\\fp_{i-1}',
    'fpm' => 'f^\\pm',
    'fpmi' => '\\fpm_i',
    'fpx' => 'f\'(t,\\x)',
    'fr' => '{f_r}',
    'fs' => 'f_s',
    'ft' => '\\dot f',
    'ftt' => '\\ddot f',
    'funcalign' => ['\\left\\lbrace\\begin{array}{ll}
	#1, & #2 \\\\[5pt]
	#3, & #4 \\\\
	\\end{array}
	\\right.', 4],
    'funcalignthree' => ['\\left\\lbrace\\begin{array}{ll}
	#1, & #2 \\\\[5pt]
	#3, & #4 \\\\[5pt]
	#5, & #6 \\\\
	\\end{array}
	\\right.', 6],
    'fv' => '\\underline{f}',
    'fx' => 'f\'',
    'fxpdx' => 'f(t,\\x+d\\x)',
    'fxx' => 'f\'\'',
    'g' => '\\gamma',
    'geev' => '\\underline{g}',
    'gh' => '{\\hat g}',
    'gigawatt' => '\\mathrm{GW}',
    'gl' => 'g_l',
    'gm' => '\\gamma^\\tminus',
    'gmtx' => '{\\mathbf{g}}',
    'goesto' => '\\to',
    'goestoas' => ['\\;\\stackrel{\\longrightarrow}{{\\scriptscriptstyle #1}}\\;', 1],
    'gp' => '\\gamma^\\tplus',
    'gpm' => '\\gamma^\\tpm',
    'gr' => 'g_r',
    'grad' => '\\nabla',
    'gradv' => '\\underline{\\grad}',
    'gram' => '\\mathrm{g}',
    'grams' => '\\text{ g}',
    'gt' => '\\dot g',
    'gtt' => '\\ddot g',
    'gv' => '\\underline{\\gamma}',
    'gvm' => '\\gv^\\tminus',
    'gvp' => '\\gv^\\tplus',
    'gx' => 'g\'',
    'gxx' => 'g\'\'',
    'h' => 'h',
    'hb' => '\\h_b',
    'hbm' => '\\hb^\\tminus',
    'hbp' => '\\hb^\\tplus',
    'hd' => '\\h_\\tdelta',
    'hdc' => '\\hd^c',
    'hdp' => '\\hd^\\tplus',
    'henry' => '\\mathrm{H}',
    'hertz' => '\\text{Hz}',
    'hh' => '{\\hat h}',
    'hl' => 'h_l',
    'hmtx' => '{\\mathbf{h}}',
    'hsubm' => '\\h_m',
    'htilde' => '\\tilde{h}',
    'hv' => '\\underline{h}',
    'ib' => '\\mathbf{i}',
    'ibox' => ['{\\text{#1}}', 1],
    'idft' => '\\oper{IDFT}',
    'idtft' => '\\oper{IDTFT}',
    'iffs' => '\\;\\Leftrightarrow\\;',
    'ifft' => '\\oper{IFFT}',
    'imagPart' => ['\\text{im}\\left\\lbrace#1\\right\\rbrace', 1],
    'imagPartSq' => ['\\text{im}^2\\left\\lbrace#1\\right\\rbrace', 1],
    'imagpart' => ['\\text{im{\\left\\lbrace#1\\right\\rbrace}}', 1],
    'imagparttext' => ['\\text{im{\\{#1\\}}}', 1],
    'impliesq' => '\\implies\\quad',
    'impliess' => '\\,\\,\\Rightarrow\\,\\,',
    'index' => ['', 1],
    'intrange' => ['#1:#2', 2],
    'intrangefour' => ['#1, #2, #3, \\ldots, #4', 4],
    'intrangethree' => ['#1, #2, \\ldots, #3', 3],
    'ints' => '\\mathbb{Z}',
    'ip' => ['\\left<#1\\right>', 1],
    'iptext' => ['\\langle #1\\rangle', 1],
    'isdef' => '\\mathrel{\\stackrel{\\mathrm{\\Delta}}{=}}',
    'isdefs' => '\\;\\isdef\\;',
    'isdefss' => '\\,\\;\\isdef\\;\\,',
    'isdeftext' => '\\mathrel{\\stackrel{\\scriptscriptstyle\\mathrm{\\Delta}}{\\scriptstyle=}}',
    'jb' => '\\mathbf{j}',
    'joule' => '\\mathrm{J}',
    'joules' => '\\text{ J}',
    'jw' => 'j \\omega',
    'kb' => '\\mathbf{k}',
    'kg' => '\\text{ kg}',
    'kiloamp' => '\\mathrm{kA}',
    'kilogram' => '\\mathrm{kg}',
    'kilohertz' => '\\text{kHz}',
    'kilohm' => '\\text{\\mathrm{k}$\\Omega$}',
    'kilojoule' => '\\mathrm{kJ}',
    'kilonewton' => '\\mathrm{kN}',
    'kilovolt' => '\\mathrm{kV}',
    'kilowatt' => '\\mathrm{kW}',
    'kv' => '\\underline{k}',
    'kvi' => '\\kv_i',
    'kvr' => '\\kv_r',
    'kvt' => '\\kv_t',
    'kz' => '\\kappa_0',
    'lam' => '\\lambda',
    'lami' => '{\\lambda_i}',
    'lb' => '\\left[',
    'lbr' => '\\left\\lbrace',
    'ldotss' => '\\ldots\\,',
    'lg' => '\\text{lg}',
    'ln' => '\\text{ln}',
    'lowpass' => '\\oper{Lowpass}',
    'lp' => '\\left(',
    'mXsoc' => '{m\\Xs/c}',
    'mXssc' => '{m\\Xs/c}',
    'makeboldmath' => ['\\text{${\\boldsymbol #1}$}', 1],
    'maxs' => '\\text{max}',
    'megahertz' => '\\text{MHz}',
    'megavolt' => '\\mathrm{MV}',
    'megawatt' => '\\mathrm{MW}',
    'megohm' => '\\text{\\mathrm{M}$\\Omega$}',
    'meters' => '\\text{ m}',
    'microamp' => '\\mu \\mathrm{A}',
    'microfarad' => '\\mu \\mathrm{F}',
    'microhenry' => '\\mu \\mathrm{H}',
    'microsec' => '\\mu\\text{sec}',
    'microvolt' => '\\text{$\\mu \\mathrm{V}$}',
    'microwatt' => '\\mu \\mathrm{W}',
    'milliamp' => '\\mathrm{mA}',
    'millifarad' => '\\mathrm{mF}',
    'millihenry' => '\\mathrm{mH}',
    'millisec' => '\\text{msec}',
    'millivolt' => '\\mathrm{mV}',
    'milliwatt' => '\\mathrm{mW}',
    'mins' => '\\text{min}',
    'mndx' => 'm',
    'mod' => ['\\lp\\text{mod}\\;#1\\rp', 1],
    'ms' => '{m_s}',
    'muTsste' => '{\\mu \\Ts/2\\e}',
    'mumTsste' => '{\\mu m\\Ts/2\\e}',
    'muoTsote' => '\\frac{\\mu(\\omega) \\Ts}{2\\e}',
    'muoTsste' => '{\\mu(\\omega) \\Ts/2\\e}',
    'muoe' => '\\frac{\\mu}{\\e}',
    'muoes' => '\\frac{\\mu}{\\e s}',
    'muomTsote' => '\\frac{\\mu(\\omega) m\\Ts}{2\\e}',
    'muomTsste' => '{\\mu(\\omega) m\\Ts/2\\e}',
    'muooes' => '\\frac{\\mu(\\omega)}{\\e s}',
    'muoote' => '\\frac{\\mu(\\omega)}{2\\e}',
    'muootesc' => '\\frac{\\scriptstyle\\mu(\\omega)}{2\\e}',
    'muostep' => '{\\lb\\mu(\\omega)/2\\e\\rb}',
    'muote' => '\\frac{\\mu}{2\\e}',
    'muotesc' => '\\frac{\\scriptstyle\\mu}{2\\e}',
    'muse' => '{\\mu/\\e}',
    'muste' => '{\\mu/2\\e}',
    'mustep' => '{\\lp\\mu/2\\e\\rp}',
    'mux' => '\\mu_x',
    'muxh' => '\\hat{\\mu}_x',
    'mybm' => '\\boldsymbol',
    'mymod' => ['\\oper{mod}\\ #1', 1],
    'nacc' => ['\\text{$\\stackrel{{\\scriptscriptstyle #1}}{#2}$}', 2],
    'nanoamp' => '\\mathrm{nA}',
    'nanofarad' => '\\mathrm{nF}',
    'nanosec' => '\\text{nsec}',
    'neb' => ' \\frac{1-r}{1+r}',
    'newton' => '\\mathrm{N}',
    'nn' => '\\nonumber',
    'nnr' => '\\nonumber \\\\',
    'norm' => ['\\left\\|\\,#1\\,\\right\\|', 1],
    'normi' => ['\\norm{#1}_\\infty', 1],
    'normtext' => [' ||\\,#1\\,|| ', 1],
    'nsixty' => 'n_{60}',
    'nv' => '\\underline{n}',
    'nyq' => '\\oper{Nyquist}',
    'ohm' => '\\text{$\\Omega$}',
    'ok' => '\\omega_k',
    'omax' => '\\omega_{\\text{max}}',
    'on' => '\\tilde{\\omega}',
    'onebyfour' => ['\\left[\\begin{array}{cccc} #1 & #2 & #3 & #4 \\end{array}\\right]', 4],
    'onebyfournts' => ['\\left[\\begin{array}{cccc}#1\\!&\\!#2\\!&\\!#3\\!&\\!#4\\end{array}\\right]', 4],
    'onebythree' => ['\\left[\\begin{array}{ccc} #1 & #2 & #3\\end{array}\\right]', 3],
    'onebythreetop' => ['\\begin{array}{r}\\onebythree{#1}{#2}{#3}\\\\[2pt]{}\\\\[2pt]{}\\end{array}', 3],
    'onebytwo' => ['\\left[\\begin{array}{cc} #1 & #2 \\end{array}\\right]', 2],
    'onebytwotop' => ['\\begin{array}{r}\\onebytwo{#1}{#2}\\\\[2pt]{}\\end{array}', 2],
    'onev' => '\\mathbf{1}',
    'onevt' => '\\onev^T',
    'oper' => ['\\text{#1}', 1],
    'order' => ['\\Oscr\\left(#1\\right)', 1],
    'ov' => '\\underline{\\omega}',
    'ovn' => '\\underline{\\tilde{\\omega}}',
    'pb' => '\\mathbf{p}',
    'pbm' => '\\pb^-',
    'pbmt' => '{\\pbm}^\\ast',
    'pbp' => '\\pb^+',
    'pbpt' => '{\\pbp}^\\ast',
    'pderiv' => ['\\frac{\\partial #1}{\\partial #2}', 2],
    'pdot' => '\\dot{p}',
    'peev' => '\\underline{p}',
    'pfend' => '$\\Box$',
    'pfendmath' => '\\Box',
    'picoamp' => '\\mathrm{pA}',
    'picofarad' => '\\mathrm{pF}',
    'picowatt' => '\\mathrm{pW}',
    'pmi' => '\\pminus_i',
    'pminus' => 'p^-',
    'pole' => 'p',
    'pom' => 'p_1^-',
    'pomn' => '\\pom(n)',
    'pomns' => '\\lb\\pomn\\rb^2',
    'poms' => '(\\pom)^2',
    'pop' => 'p_1^+',
    'poper' => ['\\frac{\\partial}{\\partial #1}', 1],
    'popn' => '\\pop(n)',
    'popns' => '\\lb\\popn\\rb^2',
    'pops' => '(\\pop)^2',
    'pp' => 'p^+',
    'ppi' => '\\pp_i',
    'pplus' => 'p^+',
    'pprime' => 'p\'',
    'pprimetx' => 'p\'(t,\\x)',
    'projop' => '\\mathbf{P}',
    'pt' => '\\dot{p}',
    'ptilde' => '\\tilde{p}',
    'ptt' => '\\ddot{p}',
    'pv' => '\\mathbf{p}',
    'pvec' => '\\underline{p}',
    'pvm' => '\\pv^-',
    'pvmt' => '{\\pvm}^\\ast',
    'pvp' => '\\pv^+',
    'pvpt' => '{\\pvp}^\\ast',
    'pvt' => '\\pv^\\ast',
    'qb' => '\\mathbf{q}',
    'qsp' => '\\ ',
    'qv' => '\\underline{q}',
    'rad' => '\\text{rad}',
    'rair' => '\\rho',
    'rb' => '\\right]',
    'rbr' => '\\right\\rbrace',
    'rc' => 'k',
    'rci' => '\\rc_i',
    'rcs' => 'k',
    'real' => '\\Re',
    'realPart' => ['\\text{re}\\left\\lbrace#1\\right\\rbrace', 1],
    'realPartSq' => ['\\text{re}^2\\left\\lbrace#1\\right\\rbrace', 1],
    'realpart' => ['\\text{re{\\left\\lbrace#1\\right\\rbrace}}', 1],
    'realparttext' => ['\\text{re{\\{#1\\}}}', 1],
    'reals' => '\\mathbb{R}',
    'relop' => ['\\,#1\\,', 1],
    'rhoejpsi' => '\\rho\\,e^{j\\psi}',
    'rhot' => '\\hat\\rho',
    'rhotozero' => '{\\rho \\to  0}',
    'rhxn' => '\\hat{r}_{x(n)}',
    'ri' => '\\R_i',
    'rms' => '\\text{RMS}',
    'ro' => '\\R_1',
    'rp' => '\\right)',
    'rpt' => '\\oper{Repeat}',
    'rr' => 's',
    'rt' => '\\R_2',
    'rth' => '\\R_3',
    'rv' => '\\underline{r}',
    'rz' => '\\R_0',
    'sR' => '\\sqrt{R}',
    'sample' => '\\oper{Sample}',
    'sc' => ['\\text{#1}', 1],
    'scale' => '\\oper{Scale}',
    'sec' => '\\text{sec}',
    'seconds' => '\\text{ s}',
    'select' => '\\oper{Downsample}',
    'set' => ['\\left\\lbrace#1\\right\\rbrace', 1],
    'shah' => '\\,\\raisebox{0.8em}{\\rotatebox{-90}{\\resizebox{1em}{1em}{{\\exists}}}}',
    'shift' => '\\oper{Shift}',
    'si' => 's_i',
    'sigmav' => '\\underline{\\sigma}',
    'simpliess' => '\\quad\\Rightarrow\\quad',
    'sinc' => '\\text{sinc}',
    'sixbyone' => ['\\left[\\sixbyonenp{#1}{#2}{#3}{#4}{#5}{#6}\\right]', 6],
    'sn' => 's_n',
    'str' => '\\oper{Stretch}',
    'tauv' => '\\underline{\\tau}',
    'tdelta' => '{\\Delta}',
    'testtilde' => ['
  \\ifx\\relax#1\\relax\\noexpand~\\else\\noexpand\\~#1\\fi', 1],
    'texttilde' => ['~', 1],
    'textunderscore' => '_',
    'thh' => '\\hat{\\theta}',
    'threebyone' => ['\\left[\\threebyonenp{#1}{#2}{#3}\\right]', 3],
    'threebyonenp' => ['\\begin{array}{c} #1 \\\\[2pt] #2 \\\\[2pt] #3\\end{array}', 3],
    'threebythree' => ['\\left[\\threebythreenp{#1}{#2}{#3}{#4}{#5}{#6}{#7}{#8}{#9}\\right]', 9],
    'threebythreenp' => ['
\\begin{array}{ccc} 
#1 & #2 & #3\\\\[2pt] 
#4 & #5 & #6\\\\[2pt] 
#7 & #8 & #9 
\\end{array}
', 9],
    'threebythreert' => ['\\left[\\begin{array}{rrr} 
#1 & #2 & #3\\\\[2pt] 
#4 & #5 & #6\\\\[2pt] 
#7 & #8 & #9 
\\end{array}\\right]', 9],
    'tminus' => '{-}',
    'tmsq' => ['[#1]^2', 1],
    'tn' => 't_n',
    'tplus' => '{+}',
    'tpm' => '{\\pm}',
    'tsixty' => 't_{60}',
    'tsw' => '\\tsixty(\\omega)',
    'twobyone' => ['\\left[\\twobyonenp{#1}{#2}\\right]', 2],
    'twobyonenp' => ['\\begin{array}{c} #1 \\\\[2pt] #2 \\end{array}', 2],
    'twobyonep' => ['\\left(\\twobyonenp{#1}{#2}\\right)', 2],
    'twobythree' => ['\\left[\\begin{array}{ccc} 
#1 & #2 & #3\\\\[5pt] 
#4 & #5 & #6
\\end{array}\\right]', 6],
    'twobythreesp' => ['\\left[\\begin{array}{ccc} 
#1 & #2 & #3\\\\[#7pt] 
#4 & #5 & #6
\\end{array}\\right]', 7],
    'twobytwo' => ['\\left[\\begin{array}{cc} #1 & #2 \\\\[2pt] #3 & #4 \\end{array}\\right]', 4],
    'twobytwonp' => ['\\begin{array}{cc} #1 & #2 \\\\[2pt] #3 & #4 \\end{array}', 4],
    'twobytwonprs' => ['\\begin{array}{cc} #1 & #2 \\\\[#5] #3 & #4 \\end{array}', 5],
    'twobytwor' => ['\\left[\\begin{array}{rr} #1 & #2 \\\\[2pt] #3 & #4 \\end{array}\\right]', 4],
    'twobytwors' => ['\\left[\\begin{array}{cc} #1 & #2 \\\\[#5] #3 & #4 \\end{array}\\right]', 5],
    'tz' => 't_0',
    'u' => 'u',
    'ub' => '\\mathbf{u}',
    'ubar' => '\\overline{u}',
    'ubarx' => '\\ubar_x',
    'ubary' => '\\ubar_y',
    'ubarz' => '\\ubar_z',
    'um' => 'u^\\tminus',
    'umtx' => '\\mathbf{u}',
    'up' => 'u^\\tplus',
    'upm' => 'u^\\pm',
    'ups' => '\\upsilon',
    'upsv' => '\\underline{\\upsilon}',
    'us' => ['\\uparrow\\!\\!#1', 1],
    'ut' => '{\\dot u}',
    'utt' => '{\\ddot u}',
    'uttt' => '{\\ddot u}',
    'utttx' => '\\utt(t,\\x)',
    'uttx' => '\\ut(t,\\x)',
    'utx' => 'u(t,\\x)',
    'uv' => '\\underline{u}',
    'vb' => 'v_b',
    'vd' => 'v_d',
    'vdc' => '\\vdelta^c',
    'vdelta' => 'v_\\tdelta',
    'vdp' => '\\vdelta^\\tplus',
    'vh' => '\\hat{v}',
    'vht' => '\\hat{\\vt}',
    'vi' => '{v_i}',
    'vin' => ['\\text{in}_{#1}', 1],
    'vio' => '\\vi(\\omega)',
    'vl' => 'v_l',
    'vls' => 'v_{ls}',
    'vm' => 'v^\\tminus',
    'vmi' => '\\vm_i',
    'vmls' => 'v_{ls}',
    'vmsl' => 'v_{sl}',
    'vn' => '\\tilde{v}',
    'vnm' => '\\vn^\\tminus',
    'vnmi' => '\\vn^\\tminus_i',
    'vnp' => '\\vn^\\tplus',
    'vnpi' => '\\vn^\\tplus_i',
    'vnpm' => '\\vn^\\pm',
    'volt' => '\\mathrm{V}',
    'vp' => 'v^\\tplus',
    'vpi' => '\\vp_i',
    'vpimo' => '\\vp_{i-1}',
    'vpm' => 'v^\\pm',
    'vpmi' => '\\vpm_i',
    'vr' => '{v_r}',
    'vro' => '\\vr(\\omega)',
    'vs' => 'v_s',
    'vsl' => 'v_{s,l}',
    'vslm' => '\\vsl^\\tminus',
    'vslp' => '\\vsl^\\tplus',
    'vsp' => '\\vs^\\tplus',
    'vsr' => 'v_{s,r}',
    'vsrm' => '\\vsr^\\tminus',
    'vsrp' => '\\vsr^\\tplus',
    'vt' => '\\dot v',
    'vtilde' => '\\tilde{v}',
    'vv' => '\\mathbf{p}',
    'vvec' => '\\underline{v}',
    'vvecl' => '\\vvec_l',
    'vvecls' => '\\vvec_{ls}',
    'vvecs' => '\\vvec_s',
    'vvecsl' => '\\vvec_{sl}',
    'vvm' => '\\vv^-',
    'vvp' => '\\vv^+',
    'vvpt' => '{\\vvp}^\\ast',
    'vvt' => '\\vv^\\ast',
    'vx' => 'v\'',
    'vxh' => '\\hat{\\sigma}_x^2',
    'watt' => '\\mathrm{W}',
    'wh' => '{\\hat \\omega}',
    'window' => '\\oper{Window}',
    'wl' => '\\omega_l',
    'wm' => '\\omega_m',
    'wmtx' => '{\\mathbf{w}}',
    'wn' => '\\tilde{\\omega_1}',
    'wrap' => '\\oper{wrap}',
    'ws' => '\\omega_s',
    'wv' => '\\underline{w}',
    'wz' => '{\\omega_0}',
    'x' => 'x',
    'xK' => '\\xv_K',
    'xW' => '\\xv_W',
    'xb' => '\\mathbf{x}',
    'xddot' => '{\\ddot x}',
    'xdot' => '{\\dot x}',
    'xh' => '{\\hat x}',
    'xht' => '\\hat{\\xt}',
    'xhtt' => '{\\hat{\\ddot x}}',
    'xhv' => '\\underline{\\hat{x}}',
    'xhva' => '\\underline{\\hat{x}}^\\ast',
    'xm' => 'x_m',
    'xmoc' => '\\frac{\\xm}{c}',
    'xmsc' => '{\\xm/c}',
    'xoc' => '\\frac{x}{c}',
    'xocsc' => '\\frac{\\scriptstyle x}{c}',
    'xp' => '\\xtilde',
    'xsc' => '{x/c}',
    'xt' => '\\dot x',
    'xtilde' => '\\tilde{x}',
    'xtt' => '\\ddot x',
    'xv' => '\\underline{x}',
    'xvddot' => '\\underline{\\xddot}',
    'xvdot' => '\\underline{\\xdot}',
    'xvl' => '\\xv_l',
    'xvls' => '\\xv_{ls}',
    'xvn' => '\\tilde{\\xv}',
    'xvs' => '\\xv_s',
    'xvsl' => '\\xv_{sl}',
    'xvt' => '\\tilde{\\xv}',
    'xz' => 'x_0',
    'y' => 'y',
    'yb' => '\\mathbf{y}',
    'yffnm' => 'y^{ff}_{n,\\mndx}',
    'yffnmom' => 'y^{ff}_{n-1,\\mndx}',
    'yfnm' => 'y^f_{n,\\mndx}',
    'yfnmmo' => 'y^f_{n,\\mndx-1}',
    'yfnmpo' => 'y^f_{n,\\mndx+1}',
    'yfull' => 'y(t,x)',
    'yh' => '\\hat y',
    'yl' => 'y_l',
    'ylt' => '\\yt_l',
    'yltt' => '\\ytt_l',
    'ylx' => 'y\'_l',
    'ylxx' => 'y\'\'_l',
    'ym' => 'y^\\tminus',
    'ymnm' => '\\ym_{n,\\mndx}',
    'ymnmmo' => '\\ym_{n,\\mndx-1}',
    'ymnmom' => '\\ym_{n-1,\\mndx}',
    'ymnmpfi' => '\\ym_{n,\\mndx+5}',
    'ymnmpo' => '\\ym_{n,\\mndx+1}',
    'ymnmpth' => '\\ym_{n,\\mndx+3}',
    'ymnpom' => '\\ym_{n+1,\\mndx}',
    'ymt' => '\\dot y^\\tminus',
    'ymx' => 'y\'^\\tminus',
    'ynm' => 'y_{n,\\mndx}',
    'ynmmo' => 'y_{n,\\mndx-1}',
    'ynmom' => 'y_{n-1,\\mndx}',
    'ynmompf' => 'y_{n-1,\\mndx+4}',
    'ynmompt' => 'y_{n-1,\\mndx+2}',
    'ynmpfi' => 'y_{n,\\mndx+5}',
    'ynmpo' => 'y_{n,\\mndx+1}',
    'ynmpth' => 'y_{n,\\mndx+3}',
    'ynpom' => 'y_{n+1,\\mndx}',
    'ynpompo' => 'y_{n+1,\\mndx+1}',
    'yp' => 'y^\\tplus',
    'ypm' => 'y^\\pm',
    'ypmt' => '\\dot y^\\pm',
    'ypmtt' => '\\ddot y^\\pm',
    'ypmx' => 'y\'^\\pm',
    'ypmxx' => 'y\'\'^\\pm',
    'ypnm' => '\\yp_{n,\\mndx}',
    'ypnmmo' => '\\yp_{n,\\mndx-1}',
    'ypnmom' => '\\yp_{n-1,\\mndx}',
    'ypnmpfi' => '\\yp_{n,\\mndx+5}',
    'ypnmpo' => '\\yp_{n,\\mndx+1}',
    'ypnmpth' => '\\yp_{n,\\mndx+3}',
    'ypnpom' => '\\yp_{n+1,\\mndx}',
    'ypt' => '\\dot y^\\tplus',
    'ypx' => 'y\'^\\tplus',
    'yr' => 'y_r',
    'yrt' => '\\yt_r',
    'yrtt' => '\\ytt_r',
    'yrttt' => '\\yttt_r',
    'yrttttt' => '{\\yttttt_r}',
    'yrx' => 'y\'_r',
    'yrxx' => 'y\'\'_r',
    'yt' => '{\\dot y}',
    'ytt' => '{\\ddot y}',
    'yttt' => '{\\dddot y}',
    'yttttt' => '{\\partial^5 y/\\partial t^5}',
    'yttx' => '{\\ddot y\'}',
    'yv' => '\\underline{y}',
    'yvec' => '{\\underline{y}}',
    'yx' => 'y\'',
    'yxx' => 'y\'\'',
    'yxxt' => '{\\dot y\'\'}',
    'yxxxx' => 'y\'\'\'\'',
    'zbox' => ['{\\boxed{#1}}', 1],
    'zboxlt' => ['\\boxed{#1}', 1],
    'zeev' => '\\underline{z}',
    'zero' => 'q',
    'zeropad' => '\\oper{ZeroPad}',
    'zerov' => '\\underline{0}',
    'zi' => 'z^{-1}',
    'zio' => 'z^{-\\cz/c(\\omega)}',
    'zmn' => 'z^{-\\nu}',
    'zmoh' => 'z^{-{1/2}}',
    'zmt' => 'z^{-2}',
    'zoh' => 'z^{1/2}',
    'zp' => 'z^\\prime',
    'zv' => '\\underline{0}',
    'zvec' => '\\underline{z}',
    'zvv' => '\\underline{\\zeev}',
);

# Prevent l2h from expanding these via \newcommand
%mathjax_protected_cmds = (
    'AK' => 1,
    'AKt' => 1,
    'AKtt' => 1,
    'AKttt' => 1,
    'AKtttt' => 1,
    'AP' => 1,
    'AW' => 1,
    'AWt' => 1,
    'AWtt' => 1,
    'AWttt' => 1,
    'AWtttt' => 1,
    'Ab' => 1,
    'Abt' => 1,
    'Acorr' => 1,
    'Ah' => 1,
    'Alias' => 1,
    'Allp' => 1,
    'AllpConsol' => 1,
    'Alpha' => 1,
    'Am' => 1,
    'Amtx' => 1,
    'Amtxt' => 1,
    'Ao' => 1,
    'Ap' => 1,
    'Ascr' => 1,
    'At' => 1,
    'Atilde' => 1,
    'Atmtx' => 1,
    'Atmtxt' => 1,
    'Att' => 1,
    'BK' => 1,
    'BW' => 1,
    'Bb' => 1,
    'Bh' => 1,
    'Bmtx' => 1,
    'Bscr' => 1,
    'Bt' => 1,
    'Btmtx' => 1,
    'CK' => 1,
    'CN' => 1,
    'CW' => 1,
    'CZeroPad' => 1,
    'Cb' => 1,
    'Chop' => 1,
    'Cmtx' => 1,
    'Cn' => 1,
    'Conv' => 1,
    'Corr' => 1,
    'Cscr' => 1,
    'Ct' => 1,
    'Ctmtx' => 1,
    'DCT' => 1,
    'DEL' => 1,
    'DFT' => 1,
    'DK' => 1,
    'DST' => 1,
    'DTFT' => 1,
    'DW' => 1,
    'Db' => 1,
    'Dec' => 1,
    'Deltab' => 1,
    'Delv' => 1,
    'Dmtx' => 1,
    'Dmtxi' => 1,
    'Dmtxt' => 1,
    'Dmtxti' => 1,
    'Dscr' => 1,
    'Dt' => 1,
    'Dtd' => 1,
    'Dtmtx' => 1,
    'E' => 1,
    'EDC' => 1,
    'EDR' => 1,
    'Eh' => 1,
    'Em' => 1,
    'Emi' => 1,
    'Emtx' => 1,
    'Emtxi' => 1,
    'Emtxt' => 1,
    'Emtxti' => 1,
    'Energy' => 1,
    'Esc' => 1,
    'Escr' => 1,
    'Ev' => 1,
    'FBCF' => 1,
    'FFCF' => 1,
    'FFT' => 1,
    'FT' => 1,
    'Fa' => 1,
    'Fb' => 1,
    'Fbold' => 1,
    'Fd' => 1,
    'Flip' => 1,
    'Fm' => 1,
    'Fp' => 1,
    'Fs' => 1,
    'Fscr' => 1,
    'Fv' => 1,
    'G' => 1,
    'Gb' => 1,
    'Geemtx' => 1,
    'Gh' => 1,
    'Gmtx' => 1,
    'Gt' => 1,
    'Gtv' => 1,
    'Gtvt' => 1,
    'Gv' => 1,
    'Gvt' => 1,
    'Gz' => 1,
    'HL' => 1,
    'Hb' => 1,
    'Hbold' => 1,
    'Hh' => 1,
    'Hha' => 1,
    'Hhl' => 1,
    'Hhs' => 1,
    'Hl' => 1,
    'Hmtx' => 1,
    'Hmtxt' => 1,
    'Hs' => 1,
    'Hscr' => 1,
    'Ht' => 1,
    'Htmtx' => 1,
    'Hv' => 1,
    'IDFT' => 1,
    'IDTFT' => 1,
    'IFFT' => 1,
    'IFT' => 1,
    'Im' => 1,
    'Imtx' => 1,
    'Interp' => 1,
    'Iscr' => 1,
    'Iv' => 1,
    'Jmtx' => 1,
    'Kmtx' => 1,
    'LBCF' => 1,
    'Lamm' => 1,
    'Laplace' => 1,
    'Linf' => 1,
    'Lmtx' => 1,
    'Lo' => 1,
    'Lone' => 1,
    'Lp' => 1,
    'Lscr' => 1,
    'Ltwo' => 1,
    'Ltwotext' => 1,
    'Lv' => 1,
    'M' => 1,
    'Mh' => 1,
    'Mmtx' => 1,
    'Na' => 1,
    'Nah' => 1,
    'Nb' => 1,
    'Nbh' => 1,
    'Nc' => 1,
    'Newtons' => 1,
    'Ngh' => 1,
    'Nh' => 1,
    'Nsc' => 1,
    'Nscr' => 1,
    'Nus' => 1,
    'Nyquist' => 1,
    'Op' => 1,
    'Oscr' => 1,
    'PInterp' => 1,
    'Pb' => 1,
    'Pbm' => 1,
    'Pbp' => 1,
    'Pd' => 1,
    'Pdc' => 1,
    'Pdp' => 1,
    'Pds' => 1,
    'Pee' => 1,
    'Ph' => 1,
    'Phd' => 1,
    'Phds' => 1,
    'Phl' => 1,
    'Pl' => 1,
    'Pm' => 1,
    'Pms' => 1,
    'Pmtx' => 1,
    'Pofs' => 1,
    'Pomo' => 1,
    'Popo' => 1,
    'Ppms' => 1,
    'Pps' => 1,
    'Ps' => 1,
    'Pscr' => 1,
    'Psm' => 1,
    'Psp' => 1,
    'Psx' => 1,
    'Ptmo' => 1,
    'Ptpo' => 1,
    'Pu' => 1,
    'Qmtx' => 1,
    'R' => 1,
    'RMM' => 1,
    'RMS' => 1,
    'RN' => 1,
    'RR' => 1,
    'RRt' => 1,
    'Ra' => 1,
    'Radius' => 1,
    'Ram' => 1,
    'Rams' => 1,
    'Rap' => 1,
    'Rapm' => 1,
    'Rapms' => 1,
    'Raps' => 1,
    'Ras' => 1,
    'Rb' => 1,
    'Rbh' => 1,
    'Rbt' => 1,
    'Rc' => 1,
    'Rcm' => 1,
    'Rcms' => 1,
    'Rcp' => 1,
    'Rcpm' => 1,
    'Rcpms' => 1,
    'Rcps' => 1,
    'Rcs' => 1,
    'Re' => 1,
    'RectWin' => 1,
    'Rejphi' => 1,
    'Repeat' => 1,
    'Rho' => 1,
    'Rhot' => 1,
    'Ri' => 1,
    'Rimo' => 1,
    'Rm' => 1,
    'Ro' => 1,
    'Rp' => 1,
    'Rpm' => 1,
    'Rpms' => 1,
    'Rs' => 1,
    'Rscr' => 1,
    'Rthree' => 1,
    'Rtube' => 1,
    'Rz' => 1,
    'STFT' => 1,
    'Sample' => 1,
    'Sb' => 1,
    'Scale' => 1,
    'Select' => 1,
    'Shift' => 1,
    'Sinc' => 1,
    'So' => 1,
    'Ssc' => 1,
    'Sscr' => 1,
    'Stretch' => 1,
    'T' => 1,
    'Tau' => 1,
    'Tb' => 1,
    'Tbi' => 1,
    'Tbit' => 1,
    'Tbt' => 1,
    'Thh' => 1,
    'Tm' => 1,
    'Tmi' => 1,
    'To' => 1,
    'Ts' => 1,
    'Tscr' => 1,
    'Tso' => 1,
    'U' => 1,
    'Ub' => 1,
    'Ubm' => 1,
    'Ubp' => 1,
    'Uc' => 1,
    'Ucms' => 1,
    'Ucpms' => 1,
    'Ucps' => 1,
    'Ucs' => 1,
    'Um' => 1,
    'Ums' => 1,
    'Umtx' => 1,
    'Umtxi' => 1,
    'Umtxt' => 1,
    'Umtxti' => 1,
    'Upms' => 1,
    'Ups' => 1,
    'Us' => 1,
    'V' => 1,
    'Va' => 1,
    'Var' => 1,
    'Vb' => 1,
    'Vd' => 1,
    'Vht' => 1,
    'Vm' => 1,
    'Vmtx' => 1,
    'Vp' => 1,
    'Vt' => 1,
    'Vv' => 1,
    'Wb' => 1,
    'Wm' => 1,
    'Wmtx' => 1,
    'Wp' => 1,
    'Wsc' => 1,
    'X' => 1,
    'Xb' => 1,
    'Xs' => 1,
    'Xscr' => 1,
    'Xv' => 1,
    'Yb' => 1,
    'Ym' => 1,
    'Yp' => 1,
    'Yv' => 1,
    'Yx' => 1,
    'ZeroPad' => 1,
    'Zeromtx' => 1,
    'Zscr' => 1,
    'Zt' => 1,
    'ab' => 1,
    'abar' => 1,
    'abs' => 1,
    'abstext' => 1,
    'ah' => 1,
    'alias' => 1,
    'amp' => 1,
    'apm' => 1,
    'approaches' => 1,
    'approxs' => 1,
    'arccosh' => 1,
    'arcsinh' => 1,
    'asinc' => 1,
    'at' => 1,
    'av' => 1,
    'avg' => 1,
    'bb' => 1,
    'beev' => 1,
    'bh' => 1,
    'biglp' => 1,
    'bigrp' => 1,
    'bl' => 1,
    'bmtx' => 1,
    'br' => 1,
    'bt' => 1,
    'bv' => 1,
    'ceil' => 1,
    'ceiltext' => 1,
    'chati' => 1,
    'chis' => 1,
    'choosenp' => 1,
    'choosep' => 1,
    'ci' => 1,
    'circonv' => 1,
    'cm' => 1,
    'cn' => 1,
    'co' => 1,
    'cola' => 1,
    'complex' => 1,
    'conj' => 1,
    'conv' => 1,
    'corrto' => 1,
    'corrtotext' => 1,
    'coul' => 1,
    'cp' => 1,
    'cpile' => 1,
    'crg' => 1,
    'crgg' => 1,
    'cscalar' => 1,
    'cv' => 1,
    'cz' => 1,
    'dB' => 1,
    'db' => 1,
    'dec' => 1,
    'degC' => 1,
    'degF' => 1,
    'degK' => 1,
    'degrees' => 1,
    'del' => 1,
    'delop' => 1,
    'deltab' => 1,
    'deltav' => 1,
    'df' => 1,
    'dft' => 1,
    'dftilde' => 1,
    'dhv' => 1,
    'diag' => 1,
    'dinv' => 1,
    'domega' => 1,
    'don' => 1,
    'dpb' => 1,
    'dpoper' => 1,
    'dqb' => 1,
    'ds' => 1,
    'dscalar' => 1,
    'dtft' => 1,
    'dv' => 1,
    'dynes' => 1,
    'e' => 1,
    'eb' => 1,
    'eh' => 1,
    'ejo' => 1,
    'ejoT' => 1,
    'ejok' => 1,
    'ejokT' => 1,
    'ejon' => 1,
    'ejonT' => 1,
    'emjo' => 1,
    'emjoT' => 1,
    'emjok' => 1,
    'emjokT' => 1,
    'emjon' => 1,
    'emtx' => 1,
    'env' => 1,
    'eps' => 1,
    'eqbydef' => 1,
    'eqmaybe' => 1,
    'eqs' => 1,
    'eqsp' => 1,
    'eqss' => 1,
    'ergs' => 1,
    'ergsns' => 1,
    'esa' => 1,
    'esam' => 1,
    'esap' => 1,
    'esiam' => 1,
    'esiap' => 1,
    'etab' => 1,
    'etabh' => 1,
    'etah' => 1,
    'etm' => 1,
    'ev' => 1,
    'farad' => 1,
    'fd' => 1,
    'fft' => 1,
    'fh' => 1,
    'fhmimo' => 1,
    'fhpi' => 1,
    'fhpimo' => 1,
    'fivebyone' => 1,
    'fivebyonenp' => 1,
    'fivebyonens' => 1,
    'fl' => 1,
    'flip' => 1,
    'floor' => 1,
    'floortext' => 1,
    'floortextop' => 1,
    'fm' => 1,
    'fmax' => 1,
    'fmi' => 1,
    'fmimo' => 1,
    'fn' => 1,
    'fnm' => 1,
    'fnmi' => 1,
    'fnmimo' => 1,
    'fnp' => 1,
    'fnpi' => 1,
    'fnpimo' => 1,
    'fnpm' => 1,
    'fofx' => 1,
    'foop' => 1,
    'foot' => 1,
    'fourbyone' => 1,
    'fourbyonenp' => 1,
    'fp' => 1,
    'fpi' => 1,
    'fpimo' => 1,
    'fpm' => 1,
    'fpmi' => 1,
    'fpx' => 1,
    'fr' => 1,
    'fs' => 1,
    'ft' => 1,
    'ftt' => 1,
    'funcalign' => 1,
    'funcalignthree' => 1,
    'fv' => 1,
    'fx' => 1,
    'fxpdx' => 1,
    'fxx' => 1,
    'g' => 1,
    'geev' => 1,
    'gh' => 1,
    'gigawatt' => 1,
    'gl' => 1,
    'gm' => 1,
    'gmtx' => 1,
    'goesto' => 1,
    'goestoas' => 1,
    'gp' => 1,
    'gpm' => 1,
    'gr' => 1,
    'grad' => 1,
    'gradv' => 1,
    'gram' => 1,
    'grams' => 1,
    'gt' => 1,
    'gtt' => 1,
    'gv' => 1,
    'gvm' => 1,
    'gvp' => 1,
    'gx' => 1,
    'gxx' => 1,
    'h' => 1,
    'hb' => 1,
    'hbm' => 1,
    'hbp' => 1,
    'hd' => 1,
    'hdc' => 1,
    'hdp' => 1,
    'henry' => 1,
    'hertz' => 1,
    'hh' => 1,
    'hl' => 1,
    'hmtx' => 1,
    'hsubm' => 1,
    'htilde' => 1,
    'hv' => 1,
    'ib' => 1,
    'ibox' => 1,
    'idft' => 1,
    'idtft' => 1,
    'iffs' => 1,
    'ifft' => 1,
    'imagPart' => 1,
    'imagPartSq' => 1,
    'imagpart' => 1,
    'imagparttext' => 1,
    'impliesq' => 1,
    'impliess' => 1,
    'intrange' => 1,
    'intrangefour' => 1,
    'intrangethree' => 1,
    'ints' => 1,
    'ip' => 1,
    'iptext' => 1,
    'isdef' => 1,
    'isdefs' => 1,
    'isdefss' => 1,
    'isdeftext' => 1,
    'jb' => 1,
    'joule' => 1,
    'joules' => 1,
    'jw' => 1,
    'kb' => 1,
    'kg' => 1,
    'kiloamp' => 1,
    'kilogram' => 1,
    'kilohertz' => 1,
    'kilohm' => 1,
    'kilojoule' => 1,
    'kilonewton' => 1,
    'kilovolt' => 1,
    'kilowatt' => 1,
    'kv' => 1,
    'kvi' => 1,
    'kvr' => 1,
    'kvt' => 1,
    'kz' => 1,
    'lam' => 1,
    'lami' => 1,
    'lb' => 1,
    'lbr' => 1,
    'ldotss' => 1,
    'lg' => 1,
    'ln' => 1,
    'lowpass' => 1,
    'lp' => 1,
    'mXsoc' => 1,
    'mXssc' => 1,
    'makeboldmath' => 1,
    'maxs' => 1,
    'megahertz' => 1,
    'megavolt' => 1,
    'megawatt' => 1,
    'megohm' => 1,
    'meters' => 1,
    'microamp' => 1,
    'microfarad' => 1,
    'microhenry' => 1,
    'microsec' => 1,
    'microvolt' => 1,
    'microwatt' => 1,
    'milliamp' => 1,
    'millifarad' => 1,
    'millihenry' => 1,
    'millisec' => 1,
    'millivolt' => 1,
    'milliwatt' => 1,
    'mins' => 1,
    'mndx' => 1,
    'mod' => 1,
    'ms' => 1,
    'muTsste' => 1,
    'mumTsste' => 1,
    'muoTsote' => 1,
    'muoTsste' => 1,
    'muoe' => 1,
    'muoes' => 1,
    'muomTsote' => 1,
    'muomTsste' => 1,
    'muooes' => 1,
    'muoote' => 1,
    'muootesc' => 1,
    'muostep' => 1,
    'muote' => 1,
    'muotesc' => 1,
    'muse' => 1,
    'muste' => 1,
    'mustep' => 1,
    'mux' => 1,
    'muxh' => 1,
    'mybm' => 1,
    'mymod' => 1,
    'nacc' => 1,
    'nanoamp' => 1,
    'nanofarad' => 1,
    'nanosec' => 1,
    'neb' => 1,
    'newton' => 1,
    'nn' => 1,
    'nnr' => 1,
    'norm' => 1,
    'normi' => 1,
    'normtext' => 1,
    'nsixty' => 1,
    'nv' => 1,
    'nyq' => 1,
    'ohm' => 1,
    'ok' => 1,
    'omax' => 1,
    'on' => 1,
    'onebyfour' => 1,
    'onebyfournts' => 1,
    'onebythree' => 1,
    'onebythreetop' => 1,
    'onebytwo' => 1,
    'onebytwotop' => 1,
    'onev' => 1,
    'onevt' => 1,
    'oper' => 1,
    'order' => 1,
    'ov' => 1,
    'ovn' => 1,
    'pb' => 1,
    'pbm' => 1,
    'pbmt' => 1,
    'pbp' => 1,
    'pbpt' => 1,
    'pderiv' => 1,
    'pdot' => 1,
    'peev' => 1,
    'pfend' => 1,
    'pfendmath' => 1,
    'picoamp' => 1,
    'picofarad' => 1,
    'picowatt' => 1,
    'pmi' => 1,
    'pminus' => 1,
    'pole' => 1,
    'pom' => 1,
    'pomn' => 1,
    'pomns' => 1,
    'poms' => 1,
    'pop' => 1,
    'poper' => 1,
    'popn' => 1,
    'popns' => 1,
    'pops' => 1,
    'pp' => 1,
    'ppi' => 1,
    'pplus' => 1,
    'pprime' => 1,
    'pprimetx' => 1,
    'projop' => 1,
    'pt' => 1,
    'ptilde' => 1,
    'ptt' => 1,
    'pv' => 1,
    'pvec' => 1,
    'pvm' => 1,
    'pvmt' => 1,
    'pvp' => 1,
    'pvpt' => 1,
    'pvt' => 1,
    'qb' => 1,
    'qsp' => 1,
    'qv' => 1,
    'rad' => 1,
    'rair' => 1,
    'rb' => 1,
    'rbr' => 1,
    'rc' => 1,
    'rci' => 1,
    'rcs' => 1,
    'real' => 1,
    'realPart' => 1,
    'realPartSq' => 1,
    'realpart' => 1,
    'realparttext' => 1,
    'reals' => 1,
    'relop' => 1,
    'rhoejpsi' => 1,
    'rhot' => 1,
    'rhotozero' => 1,
    'rhxn' => 1,
    'ri' => 1,
    'rms' => 1,
    'ro' => 1,
    'rp' => 1,
    'rpt' => 1,
    'rr' => 1,
    'rt' => 1,
    'rth' => 1,
    'rv' => 1,
    'rz' => 1,
    'sR' => 1,
    'sample' => 1,
    'scale' => 1,
    'sec' => 1,
    'seconds' => 1,
    'select' => 1,
    'set' => 1,
    'shah' => 1,
    'shift' => 1,
    'si' => 1,
    'sigmav' => 1,
    'simpliess' => 1,
    'sinc' => 1,
    'sixbyone' => 1,
    'sn' => 1,
    'str' => 1,
    'tauv' => 1,
    'tdelta' => 1,
    'testtilde' => 1,
    'thh' => 1,
    'threebyone' => 1,
    'threebyonenp' => 1,
    'threebythree' => 1,
    'threebythreenp' => 1,
    'threebythreert' => 1,
    'tminus' => 1,
    'tmsq' => 1,
    'tn' => 1,
    'tplus' => 1,
    'tpm' => 1,
    'tsixty' => 1,
    'tsw' => 1,
    'twobyone' => 1,
    'twobyonenp' => 1,
    'twobyonep' => 1,
    'twobythree' => 1,
    'twobythreesp' => 1,
    'twobytwo' => 1,
    'twobytwonp' => 1,
    'twobytwonprs' => 1,
    'twobytwor' => 1,
    'twobytwors' => 1,
    'tz' => 1,
    'u' => 1,
    'ub' => 1,
    'ubar' => 1,
    'ubarx' => 1,
    'ubary' => 1,
    'ubarz' => 1,
    'um' => 1,
    'umtx' => 1,
    'up' => 1,
    'upm' => 1,
    'ups' => 1,
    'upsv' => 1,
    'us' => 1,
    'ut' => 1,
    'utt' => 1,
    'uttt' => 1,
    'utttx' => 1,
    'uttx' => 1,
    'utx' => 1,
    'uv' => 1,
    'vb' => 1,
    'vd' => 1,
    'vdc' => 1,
    'vdelta' => 1,
    'vdp' => 1,
    'vh' => 1,
    'vht' => 1,
    'vi' => 1,
    'vin' => 1,
    'vio' => 1,
    'vl' => 1,
    'vls' => 1,
    'vm' => 1,
    'vmi' => 1,
    'vmls' => 1,
    'vmsl' => 1,
    'vn' => 1,
    'vnm' => 1,
    'vnmi' => 1,
    'vnp' => 1,
    'vnpi' => 1,
    'vnpm' => 1,
    'volt' => 1,
    'vp' => 1,
    'vpi' => 1,
    'vpimo' => 1,
    'vpm' => 1,
    'vpmi' => 1,
    'vr' => 1,
    'vro' => 1,
    'vs' => 1,
    'vsl' => 1,
    'vslm' => 1,
    'vslp' => 1,
    'vsp' => 1,
    'vsr' => 1,
    'vsrm' => 1,
    'vsrp' => 1,
    'vt' => 1,
    'vtilde' => 1,
    'vv' => 1,
    'vvec' => 1,
    'vvecl' => 1,
    'vvecls' => 1,
    'vvecs' => 1,
    'vvecsl' => 1,
    'vvm' => 1,
    'vvp' => 1,
    'vvpt' => 1,
    'vvt' => 1,
    'vx' => 1,
    'vxh' => 1,
    'watt' => 1,
    'wh' => 1,
    'window' => 1,
    'wl' => 1,
    'wm' => 1,
    'wmtx' => 1,
    'wn' => 1,
    'wrap' => 1,
    'ws' => 1,
    'wv' => 1,
    'wz' => 1,
    'x' => 1,
    'xK' => 1,
    'xW' => 1,
    'xb' => 1,
    'xddot' => 1,
    'xdot' => 1,
    'xh' => 1,
    'xht' => 1,
    'xhtt' => 1,
    'xhv' => 1,
    'xhva' => 1,
    'xm' => 1,
    'xmoc' => 1,
    'xmsc' => 1,
    'xoc' => 1,
    'xocsc' => 1,
    'xp' => 1,
    'xsc' => 1,
    'xt' => 1,
    'xtilde' => 1,
    'xtt' => 1,
    'xv' => 1,
    'xvddot' => 1,
    'xvdot' => 1,
    'xvl' => 1,
    'xvls' => 1,
    'xvn' => 1,
    'xvs' => 1,
    'xvsl' => 1,
    'xvt' => 1,
    'xz' => 1,
    'y' => 1,
    'yb' => 1,
    'yffnm' => 1,
    'yffnmom' => 1,
    'yfnm' => 1,
    'yfnmmo' => 1,
    'yfnmpo' => 1,
    'yfull' => 1,
    'yh' => 1,
    'yl' => 1,
    'ylt' => 1,
    'yltt' => 1,
    'ylx' => 1,
    'ylxx' => 1,
    'ym' => 1,
    'ymnm' => 1,
    'ymnmmo' => 1,
    'ymnmom' => 1,
    'ymnmpfi' => 1,
    'ymnmpo' => 1,
    'ymnmpth' => 1,
    'ymnpom' => 1,
    'ymt' => 1,
    'ymx' => 1,
    'ynm' => 1,
    'ynmmo' => 1,
    'ynmom' => 1,
    'ynmompf' => 1,
    'ynmompt' => 1,
    'ynmpfi' => 1,
    'ynmpo' => 1,
    'ynmpth' => 1,
    'ynpom' => 1,
    'ynpompo' => 1,
    'yp' => 1,
    'ypm' => 1,
    'ypmt' => 1,
    'ypmtt' => 1,
    'ypmx' => 1,
    'ypmxx' => 1,
    'ypnm' => 1,
    'ypnmmo' => 1,
    'ypnmom' => 1,
    'ypnmpfi' => 1,
    'ypnmpo' => 1,
    'ypnmpth' => 1,
    'ypnpom' => 1,
    'ypt' => 1,
    'ypx' => 1,
    'yr' => 1,
    'yrt' => 1,
    'yrtt' => 1,
    'yrttt' => 1,
    'yrttttt' => 1,
    'yrx' => 1,
    'yrxx' => 1,
    'yt' => 1,
    'ytt' => 1,
    'yttt' => 1,
    'yttttt' => 1,
    'yttx' => 1,
    'yv' => 1,
    'yvec' => 1,
    'yx' => 1,
    'yxx' => 1,
    'yxxt' => 1,
    'yxxxx' => 1,
    'zbox' => 1,
    'zboxlt' => 1,
    'zeev' => 1,
    'zero' => 1,
    'zeropad' => 1,
    'zerov' => 1,
    'zi' => 1,
    'zio' => 1,
    'zmn' => 1,
    'zmoh' => 1,
    'zmt' => 1,
    'zoh' => 1,
    'zp' => 1,
    'zv' => 1,
    'zvec' => 1,
    'zvv' => 1,
);

# ============================================================
# MathJax pass-through helper functions
# ============================================================

# Helper: 0-arg MathJax passthrough
sub _mathjax_pass0 {
    my $cmd = shift; local($_) = @_;
    return ($USE_MATHJAX ? "\\\@#\@\@$cmd " : "") . $_;
}

# Helper: 1-arg MathJax passthrough
sub _mathjax_pass1 {
    my $cmd = shift; local($_) = @_;
    if ($USE_MATHJAX) {
        my $arg = '';
        s/$next_pair_pr_rx/$arg = $2;''/eo
            || s/$next_pair_rx/$arg = $2;''/eo
            || ($arg = &missing_braces);
        return "\\\@#\@\@$cmd\{$arg\}" . $_;
    }
    $_;
}

# Helper: 2-arg MathJax passthrough
sub _mathjax_pass2 {
    my $cmd = shift; local($_) = @_;
    if ($USE_MATHJAX) {
        my ($a1, $a2) = ('', '');
        s/$next_pair_pr_rx/$a1 = $2;''/eo
            || s/$next_pair_rx/$a1 = $2;''/eo
            || ($a1 = &missing_braces);
        s/$next_pair_pr_rx/$a2 = $2;''/eo
            || s/$next_pair_rx/$a2 = $2;''/eo
            || ($a2 = &missing_braces);
        return "\\\@#\@\@$cmd\{$a1\}\{$a2\}" . $_;
    }
    $_;
}

# Helper: N-arg MathJax passthrough
sub _mathjax_passN {
    my $cmd = shift; my $n = shift; local($_) = @_;
    if ($USE_MATHJAX) {
        my @args;
        for my $i (1..$n) {
            my $arg = '';
            s/$next_pair_pr_rx/$arg = $2;''/eo
                || s/$next_pair_rx/$arg = $2;''/eo
                || ($arg = &missing_braces);
            push @args, $arg;
        }
        my $argstr = join('', map { "\{$_\}" } @args);
        return "\\\@#\@\@$cmd$argstr" . $_;
    }
    $_;
}

# ============================================================
# Compact do_cmd_* wrappers
# ============================================================

sub do_cmd_AK { _mathjax_pass0('AK', @_) }
sub do_cmd_AKt { _mathjax_pass0('AKt', @_) }
sub do_cmd_AKtt { _mathjax_pass0('AKtt', @_) }
sub do_cmd_AKttt { _mathjax_pass0('AKttt', @_) }
sub do_cmd_AKtttt { _mathjax_pass0('AKtttt', @_) }
sub do_cmd_AP { _mathjax_pass2('AP', @_) }
sub do_cmd_AW { _mathjax_pass0('AW', @_) }
sub do_cmd_AWt { _mathjax_pass0('AWt', @_) }
sub do_cmd_AWtt { _mathjax_pass0('AWtt', @_) }
sub do_cmd_AWttt { _mathjax_pass0('AWttt', @_) }
sub do_cmd_AWtttt { _mathjax_pass0('AWtttt', @_) }
sub do_cmd_Ab { _mathjax_pass0('Ab', @_) }
sub do_cmd_Abt { _mathjax_pass0('Abt', @_) }
sub do_cmd_Acorr { _mathjax_pass0('Acorr', @_) }
sub do_cmd_Ah { _mathjax_pass0('Ah', @_) }
sub do_cmd_Alias { _mathjax_pass0('Alias', @_) }
sub do_cmd_Allp { _mathjax_pass0('Allp', @_) }
sub do_cmd_AllpConsol { _mathjax_pass0('AllpConsol', @_) }
sub do_cmd_Alpha { _mathjax_pass0('Alpha', @_) }
sub do_cmd_Am { _mathjax_pass0('Am', @_) }
sub do_cmd_Amtx { _mathjax_pass0('Amtx', @_) }
sub do_cmd_Amtxt { _mathjax_pass0('Amtxt', @_) }
sub do_cmd_Ao { _mathjax_pass0('Ao', @_) }
sub do_cmd_Ap { _mathjax_pass0('Ap', @_) }
sub do_cmd_Ascr { _mathjax_pass0('Ascr', @_) }
sub do_cmd_At { _mathjax_pass0('At', @_) }
sub do_cmd_Atilde { _mathjax_pass0('Atilde', @_) }
sub do_cmd_Atmtx { _mathjax_pass0('Atmtx', @_) }
sub do_cmd_Atmtxt { _mathjax_pass0('Atmtxt', @_) }
sub do_cmd_Att { _mathjax_pass0('Att', @_) }
sub do_cmd_BK { _mathjax_pass0('BK', @_) }
sub do_cmd_BW { _mathjax_pass0('BW', @_) }
sub do_cmd_Bb { _mathjax_pass0('Bb', @_) }
sub do_cmd_Bh { _mathjax_pass0('Bh', @_) }
sub do_cmd_Bmtx { _mathjax_pass0('Bmtx', @_) }
sub do_cmd_Bscr { _mathjax_pass0('Bscr', @_) }
sub do_cmd_Bt { _mathjax_pass0('Bt', @_) }
sub do_cmd_Btmtx { _mathjax_pass0('Btmtx', @_) }
sub do_cmd_CK { _mathjax_pass0('CK', @_) }
sub do_cmd_CN { _mathjax_pass0('CN', @_) }
sub do_cmd_CW { _mathjax_pass0('CW', @_) }
sub do_cmd_CZeroPad { _mathjax_pass0('CZeroPad', @_) }
sub do_cmd_Cb { _mathjax_pass0('Cb', @_) }
sub do_cmd_Chop { _mathjax_pass0('Chop', @_) }
sub do_cmd_Cmtx { _mathjax_pass0('Cmtx', @_) }
sub do_cmd_Cn { _mathjax_pass0('Cn', @_) }
sub do_cmd_Conv { _mathjax_pass0('Conv', @_) }
sub do_cmd_Corr { _mathjax_pass0('Corr', @_) }
sub do_cmd_Cscr { _mathjax_pass0('Cscr', @_) }
sub do_cmd_Ct { _mathjax_pass0('Ct', @_) }
sub do_cmd_Ctmtx { _mathjax_pass0('Ctmtx', @_) }
sub do_cmd_DCT { _mathjax_pass0('DCT', @_) }
sub do_cmd_DEL { _mathjax_pass1('DEL', @_) }
sub do_cmd_DFT { _mathjax_pass0('DFT', @_) }
sub do_cmd_DK { _mathjax_pass0('DK', @_) }
sub do_cmd_DST { _mathjax_pass0('DST', @_) }
sub do_cmd_DTFT { _mathjax_pass0('DTFT', @_) }
sub do_cmd_DW { _mathjax_pass0('DW', @_) }
sub do_cmd_Db { _mathjax_pass0('Db', @_) }
sub do_cmd_Dec { _mathjax_pass0('Dec', @_) }
sub do_cmd_Deltab { _mathjax_pass0('Deltab', @_) }
sub do_cmd_Delv { _mathjax_pass0('Delv', @_) }
sub do_cmd_Dmtx { _mathjax_pass0('Dmtx', @_) }
sub do_cmd_Dmtxi { _mathjax_pass0('Dmtxi', @_) }
sub do_cmd_Dmtxt { _mathjax_pass0('Dmtxt', @_) }
sub do_cmd_Dmtxti { _mathjax_pass0('Dmtxti', @_) }
sub do_cmd_Dscr { _mathjax_pass0('Dscr', @_) }
sub do_cmd_Dt { _mathjax_pass0('Dt', @_) }
sub do_cmd_Dtd { _mathjax_pass0('Dtd', @_) }
sub do_cmd_Dtmtx { _mathjax_pass0('Dtmtx', @_) }
sub do_cmd_E { _mathjax_pass1('E', @_) }
sub do_cmd_EDC { _mathjax_pass0('EDC', @_) }
sub do_cmd_EDR { _mathjax_pass0('EDR', @_) }
sub do_cmd_Eh { _mathjax_pass0('Eh', @_) }
sub do_cmd_Em { _mathjax_pass0('Em', @_) }
sub do_cmd_Emi { _mathjax_pass0('Emi', @_) }
sub do_cmd_Emtx { _mathjax_pass0('Emtx', @_) }
sub do_cmd_Emtxi { _mathjax_pass0('Emtxi', @_) }
sub do_cmd_Emtxt { _mathjax_pass0('Emtxt', @_) }
sub do_cmd_Emtxti { _mathjax_pass0('Emtxti', @_) }
sub do_cmd_Energy { _mathjax_pass0('Energy', @_) }
sub do_cmd_Esc { _mathjax_pass0('Esc', @_) }
sub do_cmd_Escr { _mathjax_pass0('Escr', @_) }
sub do_cmd_Ev { _mathjax_pass1('Ev', @_) }
sub do_cmd_FBCF { _mathjax_pass2('FBCF', @_) }
sub do_cmd_FFCF { _mathjax_pass2('FFCF', @_) }
sub do_cmd_FFT { _mathjax_pass0('FFT', @_) }
sub do_cmd_FT { _mathjax_pass0('FT', @_) }
sub do_cmd_Fa { _mathjax_pass0('Fa', @_) }
sub do_cmd_Fb { _mathjax_pass0('Fb', @_) }
sub do_cmd_Fbold { _mathjax_pass0('Fbold', @_) }
sub do_cmd_Fd { _mathjax_pass0('Fd', @_) }
sub do_cmd_Flip { _mathjax_pass0('Flip', @_) }
sub do_cmd_Fm { _mathjax_pass0('Fm', @_) }
sub do_cmd_Fp { _mathjax_pass0('Fp', @_) }
sub do_cmd_Fs { _mathjax_pass0('Fs', @_) }
sub do_cmd_Fscr { _mathjax_pass0('Fscr', @_) }
sub do_cmd_Fv { _mathjax_pass0('Fv', @_) }
sub do_cmd_G { _mathjax_pass0('G', @_) }
sub do_cmd_Gb { _mathjax_pass0('Gb', @_) }
sub do_cmd_Geemtx { _mathjax_pass0('Geemtx', @_) }
sub do_cmd_Gh { _mathjax_pass0('Gh', @_) }
sub do_cmd_Gmtx { _mathjax_pass0('Gmtx', @_) }
sub do_cmd_Gt { _mathjax_pass0('Gt', @_) }
sub do_cmd_Gtv { _mathjax_pass0('Gtv', @_) }
sub do_cmd_Gtvt { _mathjax_pass0('Gtvt', @_) }
sub do_cmd_Gv { _mathjax_pass0('Gv', @_) }
sub do_cmd_Gvt { _mathjax_pass0('Gvt', @_) }
sub do_cmd_Gz { _mathjax_pass0('Gz', @_) }
sub do_cmd_HL { _mathjax_pass0('HL', @_) }
sub do_cmd_Hb { _mathjax_pass0('Hb', @_) }
sub do_cmd_Hbold { _mathjax_pass0('Hbold', @_) }
sub do_cmd_Hh { _mathjax_pass0('Hh', @_) }
sub do_cmd_Hha { _mathjax_pass0('Hha', @_) }
sub do_cmd_Hhl { _mathjax_pass0('Hhl', @_) }
sub do_cmd_Hhs { _mathjax_pass0('Hhs', @_) }
sub do_cmd_Hl { _mathjax_pass0('Hl', @_) }
sub do_cmd_Hmtx { _mathjax_pass0('Hmtx', @_) }
sub do_cmd_Hmtxt { _mathjax_pass0('Hmtxt', @_) }
sub do_cmd_Hs { _mathjax_pass0('Hs', @_) }
sub do_cmd_Hscr { _mathjax_pass0('Hscr', @_) }
sub do_cmd_Ht { _mathjax_pass0('Ht', @_) }
sub do_cmd_Htmtx { _mathjax_pass0('Htmtx', @_) }
sub do_cmd_Hv { _mathjax_pass0('Hv', @_) }
sub do_cmd_IDFT { _mathjax_pass0('IDFT', @_) }
sub do_cmd_IDTFT { _mathjax_pass0('IDTFT', @_) }
sub do_cmd_IFFT { _mathjax_pass0('IFFT', @_) }
sub do_cmd_IFT { _mathjax_pass0('IFT', @_) }
sub do_cmd_Im { _mathjax_pass0('Im', @_) }
sub do_cmd_Imtx { _mathjax_pass0('Imtx', @_) }
sub do_cmd_Interp { _mathjax_pass0('Interp', @_) }
sub do_cmd_Iscr { _mathjax_pass0('Iscr', @_) }
sub do_cmd_Iv { _mathjax_pass0('Iv', @_) }
sub do_cmd_Jmtx { _mathjax_pass0('Jmtx', @_) }
sub do_cmd_Kmtx { _mathjax_pass0('Kmtx', @_) }
sub do_cmd_LBCF { _mathjax_passN('LBCF', 3, @_) }
sub do_cmd_Lamm { _mathjax_pass0('Lamm', @_) }
sub do_cmd_Laplace { _mathjax_pass0('Laplace', @_) }
sub do_cmd_Linf { _mathjax_pass0('Linf', @_) }
sub do_cmd_Lmtx { _mathjax_pass0('Lmtx', @_) }
sub do_cmd_Lo { _mathjax_pass0('Lo', @_) }
sub do_cmd_Lone { _mathjax_pass0('Lone', @_) }
sub do_cmd_Lp { _mathjax_pass0('Lp', @_) }
sub do_cmd_Lscr { _mathjax_pass0('Lscr', @_) }
sub do_cmd_Ltwo { _mathjax_pass0('Ltwo', @_) }
sub do_cmd_Ltwotext { _mathjax_pass0('Ltwotext', @_) }
sub do_cmd_Lv { _mathjax_pass0('Lv', @_) }
sub do_cmd_M { _mathjax_pass0('M', @_) }
sub do_cmd_Mh { _mathjax_pass0('Mh', @_) }
sub do_cmd_Mmtx { _mathjax_pass0('Mmtx', @_) }
sub do_cmd_Na { _mathjax_pass0('Na', @_) }
sub do_cmd_Nah { _mathjax_pass0('Nah', @_) }
sub do_cmd_Nb { _mathjax_pass0('Nb', @_) }
sub do_cmd_Nbh { _mathjax_pass0('Nbh', @_) }
sub do_cmd_Nc { _mathjax_pass0('Nc', @_) }
sub do_cmd_Newtons { _mathjax_pass0('Newtons', @_) }
sub do_cmd_Ngh { _mathjax_pass0('Ngh', @_) }
sub do_cmd_Nh { _mathjax_pass0('Nh', @_) }
sub do_cmd_Nsc { _mathjax_pass0('Nsc', @_) }
sub do_cmd_Nscr { _mathjax_pass0('Nscr', @_) }
sub do_cmd_Nus { _mathjax_pass0('Nus', @_) }
sub do_cmd_Nyquist { _mathjax_pass0('Nyquist', @_) }
sub do_cmd_Op { _mathjax_pass0('Op', @_) }
sub do_cmd_Oscr { _mathjax_pass0('Oscr', @_) }
sub do_cmd_PInterp { _mathjax_pass0('PInterp', @_) }
sub do_cmd_Pb { _mathjax_pass0('Pb', @_) }
sub do_cmd_Pbm { _mathjax_pass0('Pbm', @_) }
sub do_cmd_Pbp { _mathjax_pass0('Pbp', @_) }
sub do_cmd_Pd { _mathjax_pass0('Pd', @_) }
sub do_cmd_Pdc { _mathjax_pass0('Pdc', @_) }
sub do_cmd_Pdp { _mathjax_pass0('Pdp', @_) }
sub do_cmd_Pds { _mathjax_pass0('Pds', @_) }
sub do_cmd_Pee { _mathjax_pass0('Pee', @_) }
sub do_cmd_Ph { _mathjax_pass0('Ph', @_) }
sub do_cmd_Phd { _mathjax_pass0('Phd', @_) }
sub do_cmd_Phds { _mathjax_pass0('Phds', @_) }
sub do_cmd_Phl { _mathjax_pass0('Phl', @_) }
sub do_cmd_Pl { _mathjax_pass0('Pl', @_) }
sub do_cmd_Pm { _mathjax_pass0('Pm', @_) }
sub do_cmd_Pms { _mathjax_pass0('Pms', @_) }
sub do_cmd_Pmtx { _mathjax_pass0('Pmtx', @_) }
sub do_cmd_Pofs { _mathjax_pass0('Pofs', @_) }
sub do_cmd_Pomo { _mathjax_pass0('Pomo', @_) }
sub do_cmd_Popo { _mathjax_pass0('Popo', @_) }
sub do_cmd_Ppms { _mathjax_pass0('Ppms', @_) }
sub do_cmd_Pps { _mathjax_pass0('Pps', @_) }
sub do_cmd_Ps { _mathjax_pass0('Ps', @_) }
sub do_cmd_Pscr { _mathjax_pass0('Pscr', @_) }
sub do_cmd_Psm { _mathjax_pass0('Psm', @_) }
sub do_cmd_Psp { _mathjax_pass0('Psp', @_) }
sub do_cmd_Psx { _mathjax_pass0('Psx', @_) }
sub do_cmd_Ptmo { _mathjax_pass0('Ptmo', @_) }
sub do_cmd_Ptpo { _mathjax_pass0('Ptpo', @_) }
sub do_cmd_Pu { _mathjax_pass0('Pu', @_) }
sub do_cmd_Qmtx { _mathjax_pass0('Qmtx', @_) }
sub do_cmd_R { _mathjax_pass0('R', @_) }
sub do_cmd_RMM { _mathjax_pass0('RMM', @_) }
sub do_cmd_RMS { _mathjax_pass0('RMS', @_) }
sub do_cmd_RN { _mathjax_pass0('RN', @_) }
sub do_cmd_RR { _mathjax_pass0('RR', @_) }
sub do_cmd_RRt { _mathjax_pass0('RRt', @_) }
sub do_cmd_Ra { _mathjax_pass0('Ra', @_) }
sub do_cmd_Radius { _mathjax_pass0('Radius', @_) }
sub do_cmd_Ram { _mathjax_pass0('Ram', @_) }
sub do_cmd_Rams { _mathjax_pass0('Rams', @_) }
sub do_cmd_Rap { _mathjax_pass0('Rap', @_) }
sub do_cmd_Rapm { _mathjax_pass0('Rapm', @_) }
sub do_cmd_Rapms { _mathjax_pass0('Rapms', @_) }
sub do_cmd_Raps { _mathjax_pass0('Raps', @_) }
sub do_cmd_Ras { _mathjax_pass0('Ras', @_) }
sub do_cmd_Rb { _mathjax_pass0('Rb', @_) }
sub do_cmd_Rbh { _mathjax_pass0('Rbh', @_) }
sub do_cmd_Rbt { _mathjax_pass0('Rbt', @_) }
sub do_cmd_Rc { _mathjax_pass0('Rc', @_) }
sub do_cmd_Rcm { _mathjax_pass0('Rcm', @_) }
sub do_cmd_Rcms { _mathjax_pass0('Rcms', @_) }
sub do_cmd_Rcp { _mathjax_pass0('Rcp', @_) }
sub do_cmd_Rcpm { _mathjax_pass0('Rcpm', @_) }
sub do_cmd_Rcpms { _mathjax_pass0('Rcpms', @_) }
sub do_cmd_Rcps { _mathjax_pass0('Rcps', @_) }
sub do_cmd_Rcs { _mathjax_pass0('Rcs', @_) }
sub do_cmd_Re { _mathjax_pass0('Re', @_) }
sub do_cmd_RectWin { _mathjax_pass0('RectWin', @_) }
sub do_cmd_Rejphi { _mathjax_pass0('Rejphi', @_) }
sub do_cmd_Repeat { _mathjax_pass0('Repeat', @_) }
sub do_cmd_Rho { _mathjax_pass0('Rho', @_) }
sub do_cmd_Rhot { _mathjax_pass0('Rhot', @_) }
sub do_cmd_Ri { _mathjax_pass0('Ri', @_) }
sub do_cmd_Rimo { _mathjax_pass0('Rimo', @_) }
sub do_cmd_Rm { _mathjax_pass0('Rm', @_) }
sub do_cmd_Ro { _mathjax_pass0('Ro', @_) }
sub do_cmd_Rp { _mathjax_pass0('Rp', @_) }
sub do_cmd_Rpm { _mathjax_pass0('Rpm', @_) }
sub do_cmd_Rpms { _mathjax_pass0('Rpms', @_) }
sub do_cmd_Rs { _mathjax_pass0('Rs', @_) }
sub do_cmd_Rscr { _mathjax_pass0('Rscr', @_) }
sub do_cmd_Rthree { _mathjax_pass0('Rthree', @_) }
sub do_cmd_Rtube { _mathjax_pass0('Rtube', @_) }
sub do_cmd_Rz { _mathjax_pass0('Rz', @_) }
sub do_cmd_STFT { _mathjax_pass0('STFT', @_) }
sub do_cmd_Sample { _mathjax_pass0('Sample', @_) }
sub do_cmd_Sb { _mathjax_pass0('Sb', @_) }
sub do_cmd_Scale { _mathjax_pass0('Scale', @_) }
sub do_cmd_Select { _mathjax_pass0('Select', @_) }
sub do_cmd_Shift { _mathjax_pass0('Shift', @_) }
sub do_cmd_Sinc { _mathjax_pass0('Sinc', @_) }
sub do_cmd_So { _mathjax_pass0('So', @_) }
sub do_cmd_Ssc { _mathjax_pass0('Ssc', @_) }
sub do_cmd_Sscr { _mathjax_pass0('Sscr', @_) }
sub do_cmd_Stretch { _mathjax_pass0('Stretch', @_) }
sub do_cmd_T { _mathjax_pass0('T', @_) }
sub do_cmd_Tau { _mathjax_pass0('Tau', @_) }
sub do_cmd_Tb { _mathjax_pass0('Tb', @_) }
sub do_cmd_Tbi { _mathjax_pass0('Tbi', @_) }
sub do_cmd_Tbit { _mathjax_pass0('Tbit', @_) }
sub do_cmd_Tbt { _mathjax_pass0('Tbt', @_) }
sub do_cmd_Thh { _mathjax_pass0('Thh', @_) }
sub do_cmd_Tm { _mathjax_pass0('Tm', @_) }
sub do_cmd_Tmi { _mathjax_pass0('Tmi', @_) }
sub do_cmd_To { _mathjax_pass0('To', @_) }
sub do_cmd_Ts { _mathjax_pass0('Ts', @_) }
sub do_cmd_Tscr { _mathjax_pass0('Tscr', @_) }
sub do_cmd_Tso { _mathjax_pass0('Tso', @_) }
sub do_cmd_U { _mathjax_pass0('U', @_) }
sub do_cmd_Ub { _mathjax_pass0('Ub', @_) }
sub do_cmd_Ubm { _mathjax_pass0('Ubm', @_) }
sub do_cmd_Ubp { _mathjax_pass0('Ubp', @_) }
sub do_cmd_Uc { _mathjax_pass0('Uc', @_) }
sub do_cmd_Ucms { _mathjax_pass0('Ucms', @_) }
sub do_cmd_Ucpms { _mathjax_pass0('Ucpms', @_) }
sub do_cmd_Ucps { _mathjax_pass0('Ucps', @_) }
sub do_cmd_Ucs { _mathjax_pass0('Ucs', @_) }
sub do_cmd_Um { _mathjax_pass0('Um', @_) }
sub do_cmd_Ums { _mathjax_pass0('Ums', @_) }
sub do_cmd_Umtx { _mathjax_pass0('Umtx', @_) }
sub do_cmd_Umtxi { _mathjax_pass0('Umtxi', @_) }
sub do_cmd_Umtxt { _mathjax_pass0('Umtxt', @_) }
sub do_cmd_Umtxti { _mathjax_pass0('Umtxti', @_) }
sub do_cmd_Upms { _mathjax_pass0('Upms', @_) }
sub do_cmd_Ups { _mathjax_pass0('Ups', @_) }
sub do_cmd_Us { _mathjax_pass0('Us', @_) }
sub do_cmd_V { _mathjax_pass0('V', @_) }
sub do_cmd_Va { _mathjax_pass0('Va', @_) }
sub do_cmd_Var { _mathjax_pass1('Var', @_) }
sub do_cmd_Vb { _mathjax_pass0('Vb', @_) }
sub do_cmd_Vd { _mathjax_pass0('Vd', @_) }
sub do_cmd_Vht { _mathjax_pass0('Vht', @_) }
sub do_cmd_Vm { _mathjax_pass0('Vm', @_) }
sub do_cmd_Vmtx { _mathjax_pass0('Vmtx', @_) }
sub do_cmd_Vp { _mathjax_pass0('Vp', @_) }
sub do_cmd_Vt { _mathjax_pass0('Vt', @_) }
sub do_cmd_Vv { _mathjax_pass0('Vv', @_) }
sub do_cmd_Wb { _mathjax_pass0('Wb', @_) }
sub do_cmd_Wm { _mathjax_pass0('Wm', @_) }
sub do_cmd_Wmtx { _mathjax_pass0('Wmtx', @_) }
sub do_cmd_Wp { _mathjax_pass0('Wp', @_) }
sub do_cmd_Wsc { _mathjax_pass0('Wsc', @_) }
sub do_cmd_X { _mathjax_pass0('X', @_) }
sub do_cmd_Xb { _mathjax_pass0('Xb', @_) }
sub do_cmd_Xs { _mathjax_pass0('Xs', @_) }
sub do_cmd_Xscr { _mathjax_pass0('Xscr', @_) }
sub do_cmd_Xv { _mathjax_pass0('Xv', @_) }
sub do_cmd_Yb { _mathjax_pass0('Yb', @_) }
sub do_cmd_Ym { _mathjax_pass0('Ym', @_) }
sub do_cmd_Yp { _mathjax_pass0('Yp', @_) }
sub do_cmd_Yv { _mathjax_pass0('Yv', @_) }
sub do_cmd_Yx { _mathjax_pass0('Yx', @_) }
sub do_cmd_ZeroPad { _mathjax_pass0('ZeroPad', @_) }
sub do_cmd_Zeromtx { _mathjax_pass0('Zeromtx', @_) }
sub do_cmd_Zscr { _mathjax_pass0('Zscr', @_) }
sub do_cmd_Zt { _mathjax_pass1('Zt', @_) }
sub do_cmd_ab { _mathjax_pass0('ab', @_) }
sub do_cmd_abar { _mathjax_pass0('abar', @_) }
sub do_cmd_abs { _mathjax_pass1('abs', @_) }
sub do_cmd_abstext { _mathjax_pass1('abstext', @_) }
sub do_cmd_ah { _mathjax_pass0('ah', @_) }
sub do_cmd_alias { _mathjax_pass0('alias', @_) }
sub do_cmd_amp { _mathjax_pass0('amp', @_) }
sub do_cmd_apm { _mathjax_pass0('apm', @_) }
sub do_cmd_approaches { _mathjax_pass0('approaches', @_) }
sub do_cmd_approxs { _mathjax_pass0('approxs', @_) }
sub do_cmd_arccosh { _mathjax_pass0('arccosh', @_) }
sub do_cmd_arcsinh { _mathjax_pass0('arcsinh', @_) }
sub do_cmd_asinc { _mathjax_pass0('asinc', @_) }
sub do_cmd_at { _mathjax_pass1('at', @_) }
sub do_cmd_av { _mathjax_pass0('av', @_) }
sub do_cmd_avg { _mathjax_pass0('avg', @_) }
sub do_cmd_bb { _mathjax_pass0('bb', @_) }
sub do_cmd_beev { _mathjax_pass0('beev', @_) }
sub do_cmd_bh { _mathjax_pass0('bh', @_) }
sub do_cmd_biglp { _mathjax_pass0('biglp', @_) }
sub do_cmd_bigrp { _mathjax_pass0('bigrp', @_) }
sub do_cmd_bl { _mathjax_pass0('bl', @_) }
sub do_cmd_bmtx { _mathjax_pass0('bmtx', @_) }
sub do_cmd_br { _mathjax_pass0('br', @_) }
sub do_cmd_bt { _mathjax_pass0('bt', @_) }
sub do_cmd_bv { _mathjax_pass0('bv', @_) }
sub do_cmd_ceil { _mathjax_pass1('ceil', @_) }
sub do_cmd_ceiltext { _mathjax_pass1('ceiltext', @_) }
sub do_cmd_chati { _mathjax_pass0('chati', @_) }
sub do_cmd_chis { _mathjax_pass0('chis', @_) }
sub do_cmd_choosenp { _mathjax_pass2('choosenp', @_) }
sub do_cmd_choosep { _mathjax_pass2('choosep', @_) }
sub do_cmd_ci { _mathjax_pass0('ci', @_) }
sub do_cmd_circonv { _mathjax_pass0('circonv', @_) }
sub do_cmd_cm { _mathjax_pass0('cm', @_) }
sub do_cmd_cn { _mathjax_pass0('cn', @_) }
sub do_cmd_co { _mathjax_pass0('co', @_) }
sub do_cmd_cola { _mathjax_pass0('cola', @_) }
sub do_cmd_complex { _mathjax_pass0('complex', @_) }
sub do_cmd_conj { _mathjax_pass1('conj', @_) }
sub do_cmd_conv { _mathjax_pass0('conv', @_) }
sub do_cmd_corrto { _mathjax_pass0('corrto', @_) }
sub do_cmd_corrtotext { _mathjax_pass0('corrtotext', @_) }
sub do_cmd_coul { _mathjax_pass0('coul', @_) }
sub do_cmd_cp { _mathjax_pass0('cp', @_) }
sub do_cmd_cpile { _mathjax_pass1('cpile', @_) }
sub do_cmd_crg { _mathjax_pass0('crg', @_) }
sub do_cmd_crgg { _mathjax_pass0('crgg', @_) }
sub do_cmd_cscalar { _mathjax_pass0('cscalar', @_) }
sub do_cmd_cv { _mathjax_pass0('cv', @_) }
sub do_cmd_cz { _mathjax_pass0('cz', @_) }
sub do_cmd_dB { _mathjax_pass0('dB', @_) }
sub do_cmd_db { _mathjax_pass0('db', @_) }
sub do_cmd_dec { _mathjax_pass0('dec', @_) }
sub do_cmd_degC { _mathjax_pass0('degC', @_) }
sub do_cmd_degF { _mathjax_pass0('degF', @_) }
sub do_cmd_degK { _mathjax_pass0('degK', @_) }
sub do_cmd_degrees { _mathjax_pass0('degrees', @_) }
sub do_cmd_del { _mathjax_pass0('del', @_) }
sub do_cmd_delop { _mathjax_pass1('delop', @_) }
sub do_cmd_deltab { _mathjax_pass0('deltab', @_) }
sub do_cmd_deltav { _mathjax_pass0('deltav', @_) }
sub do_cmd_df { _mathjax_pass0('df', @_) }
sub do_cmd_dft { _mathjax_pass0('dft', @_) }
sub do_cmd_dftilde { _mathjax_pass0('dftilde', @_) }
sub do_cmd_dhv { _mathjax_pass0('dhv', @_) }
sub do_cmd_diag { _mathjax_pass0('diag', @_) }
sub do_cmd_dinv { _mathjax_pass0('dinv', @_) }
sub do_cmd_domega { _mathjax_pass0('domega', @_) }
sub do_cmd_don { _mathjax_pass0('don', @_) }
sub do_cmd_dpb { _mathjax_pass0('dpb', @_) }
sub do_cmd_dpoper { _mathjax_pass1('dpoper', @_) }
sub do_cmd_dqb { _mathjax_pass0('dqb', @_) }
sub do_cmd_ds { _mathjax_pass1('ds', @_) }
sub do_cmd_dscalar { _mathjax_pass0('dscalar', @_) }
sub do_cmd_dtft { _mathjax_pass0('dtft', @_) }
sub do_cmd_dv { _mathjax_pass0('dv', @_) }
sub do_cmd_dynes { _mathjax_pass0('dynes', @_) }
sub do_cmd_e { _mathjax_pass0('e', @_) }
sub do_cmd_eb { _mathjax_pass0('eb', @_) }
sub do_cmd_eh { _mathjax_pass0('eh', @_) }
sub do_cmd_ejo { _mathjax_pass0('ejo', @_) }
sub do_cmd_ejoT { _mathjax_pass0('ejoT', @_) }
sub do_cmd_ejok { _mathjax_pass0('ejok', @_) }
sub do_cmd_ejokT { _mathjax_pass0('ejokT', @_) }
sub do_cmd_ejon { _mathjax_pass0('ejon', @_) }
sub do_cmd_ejonT { _mathjax_pass0('ejonT', @_) }
sub do_cmd_emjo { _mathjax_pass0('emjo', @_) }
sub do_cmd_emjoT { _mathjax_pass0('emjoT', @_) }
sub do_cmd_emjok { _mathjax_pass0('emjok', @_) }
sub do_cmd_emjokT { _mathjax_pass0('emjokT', @_) }
sub do_cmd_emjon { _mathjax_pass1('emjon', @_) }
sub do_cmd_emtx { _mathjax_pass0('emtx', @_) }
sub do_cmd_env { _mathjax_pass0('env', @_) }
sub do_cmd_eps { _mathjax_pass0('eps', @_) }
sub do_cmd_eqbydef { _mathjax_pass0('eqbydef', @_) }
sub do_cmd_eqmaybe { _mathjax_pass0('eqmaybe', @_) }
sub do_cmd_eqs { _mathjax_pass0('eqs', @_) }
sub do_cmd_eqsp { _mathjax_pass0('eqsp', @_) }
sub do_cmd_eqss { _mathjax_pass0('eqss', @_) }
sub do_cmd_ergs { _mathjax_pass0('ergs', @_) }
sub do_cmd_ergsns { _mathjax_pass0('ergsns', @_) }
sub do_cmd_esa { _mathjax_pass0('esa', @_) }
sub do_cmd_esam { _mathjax_pass0('esam', @_) }
sub do_cmd_esap { _mathjax_pass0('esap', @_) }
sub do_cmd_esiam { _mathjax_pass0('esiam', @_) }
sub do_cmd_esiap { _mathjax_pass0('esiap', @_) }
sub do_cmd_etab { _mathjax_pass0('etab', @_) }
sub do_cmd_etabh { _mathjax_pass0('etabh', @_) }
sub do_cmd_etah { _mathjax_pass0('etah', @_) }
sub do_cmd_etm { _mathjax_pass0('etm', @_) }
sub do_cmd_ev { _mathjax_pass0('ev', @_) }
sub do_cmd_farad { _mathjax_pass0('farad', @_) }
sub do_cmd_fd { _mathjax_pass0('fd', @_) }
sub do_cmd_fft { _mathjax_pass0('fft', @_) }
sub do_cmd_fh { _mathjax_pass0('fh', @_) }
sub do_cmd_fhmimo { _mathjax_pass0('fhmimo', @_) }
sub do_cmd_fhpi { _mathjax_pass0('fhpi', @_) }
sub do_cmd_fhpimo { _mathjax_pass0('fhpimo', @_) }
sub do_cmd_fivebyone { _mathjax_passN('fivebyone', 5, @_) }
sub do_cmd_fivebyonenp { _mathjax_passN('fivebyonenp', 5, @_) }
sub do_cmd_fivebyonens { _mathjax_passN('fivebyonens', 5, @_) }
sub do_cmd_fl { _mathjax_pass0('fl', @_) }
sub do_cmd_flip { _mathjax_pass0('flip', @_) }
sub do_cmd_floor { _mathjax_pass1('floor', @_) }
sub do_cmd_floortext { _mathjax_pass1('floortext', @_) }
sub do_cmd_floortextop { _mathjax_pass0('floortextop', @_) }
sub do_cmd_fm { _mathjax_pass0('fm', @_) }
sub do_cmd_fmax { _mathjax_pass0('fmax', @_) }
sub do_cmd_fmi { _mathjax_pass0('fmi', @_) }
sub do_cmd_fmimo { _mathjax_pass0('fmimo', @_) }
sub do_cmd_fn { _mathjax_pass0('fn', @_) }
sub do_cmd_fnm { _mathjax_pass0('fnm', @_) }
sub do_cmd_fnmi { _mathjax_pass0('fnmi', @_) }
sub do_cmd_fnmimo { _mathjax_pass0('fnmimo', @_) }
sub do_cmd_fnp { _mathjax_pass0('fnp', @_) }
sub do_cmd_fnpi { _mathjax_pass0('fnpi', @_) }
sub do_cmd_fnpimo { _mathjax_pass0('fnpimo', @_) }
sub do_cmd_fnpm { _mathjax_pass0('fnpm', @_) }
sub do_cmd_fofx { _mathjax_pass0('fofx', @_) }
sub do_cmd_foop { _mathjax_pass0('foop', @_) }
sub do_cmd_foot { _mathjax_pass0('foot', @_) }
sub do_cmd_fourbyone { _mathjax_passN('fourbyone', 4, @_) }
sub do_cmd_fourbyonenp { _mathjax_passN('fourbyonenp', 4, @_) }
sub do_cmd_fp { _mathjax_pass0('fp', @_) }
sub do_cmd_fpi { _mathjax_pass0('fpi', @_) }
sub do_cmd_fpimo { _mathjax_pass0('fpimo', @_) }
sub do_cmd_fpm { _mathjax_pass0('fpm', @_) }
sub do_cmd_fpmi { _mathjax_pass0('fpmi', @_) }
sub do_cmd_fpx { _mathjax_pass0('fpx', @_) }
sub do_cmd_fr { _mathjax_pass0('fr', @_) }
sub do_cmd_fs { _mathjax_pass0('fs', @_) }
sub do_cmd_ft { _mathjax_pass0('ft', @_) }
sub do_cmd_ftt { _mathjax_pass0('ftt', @_) }
sub do_cmd_funcalign { _mathjax_passN('funcalign', 4, @_) }
sub do_cmd_funcalignthree { _mathjax_passN('funcalignthree', 6, @_) }
sub do_cmd_fv { _mathjax_pass0('fv', @_) }
sub do_cmd_fx { _mathjax_pass0('fx', @_) }
sub do_cmd_fxpdx { _mathjax_pass0('fxpdx', @_) }
sub do_cmd_fxx { _mathjax_pass0('fxx', @_) }
sub do_cmd_g { _mathjax_pass0('g', @_) }
sub do_cmd_geev { _mathjax_pass0('geev', @_) }
sub do_cmd_gh { _mathjax_pass0('gh', @_) }
sub do_cmd_gigawatt { _mathjax_pass0('gigawatt', @_) }
sub do_cmd_gl { _mathjax_pass0('gl', @_) }
sub do_cmd_gm { _mathjax_pass0('gm', @_) }
sub do_cmd_gmtx { _mathjax_pass0('gmtx', @_) }
sub do_cmd_goesto { _mathjax_pass0('goesto', @_) }
sub do_cmd_goestoas { _mathjax_pass1('goestoas', @_) }
sub do_cmd_gp { _mathjax_pass0('gp', @_) }
sub do_cmd_gpm { _mathjax_pass0('gpm', @_) }
sub do_cmd_gr { _mathjax_pass0('gr', @_) }
sub do_cmd_grad { _mathjax_pass0('grad', @_) }
sub do_cmd_gradv { _mathjax_pass0('gradv', @_) }
sub do_cmd_gram { _mathjax_pass0('gram', @_) }
sub do_cmd_grams { _mathjax_pass0('grams', @_) }
sub do_cmd_gt { _mathjax_pass0('gt', @_) }
sub do_cmd_gtt { _mathjax_pass0('gtt', @_) }
sub do_cmd_gv { _mathjax_pass0('gv', @_) }
sub do_cmd_gvm { _mathjax_pass0('gvm', @_) }
sub do_cmd_gvp { _mathjax_pass0('gvp', @_) }
sub do_cmd_gx { _mathjax_pass0('gx', @_) }
sub do_cmd_gxx { _mathjax_pass0('gxx', @_) }
sub do_cmd_h { _mathjax_pass0('h', @_) }
sub do_cmd_hb { _mathjax_pass0('hb', @_) }
sub do_cmd_hbm { _mathjax_pass0('hbm', @_) }
sub do_cmd_hbp { _mathjax_pass0('hbp', @_) }
sub do_cmd_hd { _mathjax_pass0('hd', @_) }
sub do_cmd_hdc { _mathjax_pass0('hdc', @_) }
sub do_cmd_hdp { _mathjax_pass0('hdp', @_) }
sub do_cmd_henry { _mathjax_pass0('henry', @_) }
sub do_cmd_hertz { _mathjax_pass0('hertz', @_) }
sub do_cmd_hh { _mathjax_pass0('hh', @_) }
sub do_cmd_hl { _mathjax_pass0('hl', @_) }
sub do_cmd_hmtx { _mathjax_pass0('hmtx', @_) }
sub do_cmd_hsubm { _mathjax_pass0('hsubm', @_) }
sub do_cmd_htilde { _mathjax_pass0('htilde', @_) }
sub do_cmd_hv { _mathjax_pass0('hv', @_) }
sub do_cmd_ib { _mathjax_pass0('ib', @_) }
sub do_cmd_ibox { _mathjax_pass1('ibox', @_) }
sub do_cmd_idft { _mathjax_pass0('idft', @_) }
sub do_cmd_idtft { _mathjax_pass0('idtft', @_) }
sub do_cmd_iffs { _mathjax_pass0('iffs', @_) }
sub do_cmd_ifft { _mathjax_pass0('ifft', @_) }
sub do_cmd_imagPart { _mathjax_pass1('imagPart', @_) }
sub do_cmd_imagPartSq { _mathjax_pass1('imagPartSq', @_) }
sub do_cmd_imagpart { _mathjax_pass1('imagpart', @_) }
sub do_cmd_imagparttext { _mathjax_pass1('imagparttext', @_) }
sub do_cmd_impliesq { _mathjax_pass0('impliesq', @_) }
sub do_cmd_impliess { _mathjax_pass0('impliess', @_) }
sub do_cmd_intrange { _mathjax_pass2('intrange', @_) }
sub do_cmd_intrangefour { _mathjax_passN('intrangefour', 4, @_) }
sub do_cmd_intrangethree { _mathjax_passN('intrangethree', 3, @_) }
sub do_cmd_ints { _mathjax_pass0('ints', @_) }
sub do_cmd_ip { _mathjax_pass1('ip', @_) }
sub do_cmd_iptext { _mathjax_pass1('iptext', @_) }
sub do_cmd_isdef { _mathjax_pass0('isdef', @_) }
sub do_cmd_isdefs { _mathjax_pass0('isdefs', @_) }
sub do_cmd_isdefss { _mathjax_pass0('isdefss', @_) }
sub do_cmd_isdeftext { _mathjax_pass0('isdeftext', @_) }
sub do_cmd_jb { _mathjax_pass0('jb', @_) }
sub do_cmd_joule { _mathjax_pass0('joule', @_) }
sub do_cmd_joules { _mathjax_pass0('joules', @_) }
sub do_cmd_jw { _mathjax_pass0('jw', @_) }
sub do_cmd_kb { _mathjax_pass0('kb', @_) }
sub do_cmd_kg { _mathjax_pass0('kg', @_) }
sub do_cmd_kiloamp { _mathjax_pass0('kiloamp', @_) }
sub do_cmd_kilogram { _mathjax_pass0('kilogram', @_) }
sub do_cmd_kilohertz { _mathjax_pass0('kilohertz', @_) }
sub do_cmd_kilohm { _mathjax_pass0('kilohm', @_) }
sub do_cmd_kilojoule { _mathjax_pass0('kilojoule', @_) }
sub do_cmd_kilonewton { _mathjax_pass0('kilonewton', @_) }
sub do_cmd_kilovolt { _mathjax_pass0('kilovolt', @_) }
sub do_cmd_kilowatt { _mathjax_pass0('kilowatt', @_) }
sub do_cmd_kv { _mathjax_pass0('kv', @_) }
sub do_cmd_kvi { _mathjax_pass0('kvi', @_) }
sub do_cmd_kvr { _mathjax_pass0('kvr', @_) }
sub do_cmd_kvt { _mathjax_pass0('kvt', @_) }
sub do_cmd_kz { _mathjax_pass0('kz', @_) }
sub do_cmd_lam { _mathjax_pass0('lam', @_) }
sub do_cmd_lami { _mathjax_pass0('lami', @_) }
sub do_cmd_lb { _mathjax_pass0('lb', @_) }
sub do_cmd_lbr { _mathjax_pass0('lbr', @_) }
sub do_cmd_ldotss { _mathjax_pass0('ldotss', @_) }
sub do_cmd_lg { _mathjax_pass0('lg', @_) }
sub do_cmd_ln { _mathjax_pass0('ln', @_) }
sub do_cmd_lowpass { _mathjax_pass0('lowpass', @_) }
sub do_cmd_lp { _mathjax_pass0('lp', @_) }
sub do_cmd_mXsoc { _mathjax_pass0('mXsoc', @_) }
sub do_cmd_mXssc { _mathjax_pass0('mXssc', @_) }
sub do_cmd_makeboldmath { _mathjax_pass1('makeboldmath', @_) }
sub do_cmd_maxs { _mathjax_pass0('maxs', @_) }
sub do_cmd_megahertz { _mathjax_pass0('megahertz', @_) }
sub do_cmd_megavolt { _mathjax_pass0('megavolt', @_) }
sub do_cmd_megawatt { _mathjax_pass0('megawatt', @_) }
sub do_cmd_megohm { _mathjax_pass0('megohm', @_) }
sub do_cmd_meters { _mathjax_pass0('meters', @_) }
sub do_cmd_microamp { _mathjax_pass0('microamp', @_) }
sub do_cmd_microfarad { _mathjax_pass0('microfarad', @_) }
sub do_cmd_microhenry { _mathjax_pass0('microhenry', @_) }
sub do_cmd_microsec { _mathjax_pass0('microsec', @_) }
sub do_cmd_microvolt { _mathjax_pass0('microvolt', @_) }
sub do_cmd_microwatt { _mathjax_pass0('microwatt', @_) }
sub do_cmd_milliamp { _mathjax_pass0('milliamp', @_) }
sub do_cmd_millifarad { _mathjax_pass0('millifarad', @_) }
sub do_cmd_millihenry { _mathjax_pass0('millihenry', @_) }
sub do_cmd_millisec { _mathjax_pass0('millisec', @_) }
sub do_cmd_millivolt { _mathjax_pass0('millivolt', @_) }
sub do_cmd_milliwatt { _mathjax_pass0('milliwatt', @_) }
sub do_cmd_mins { _mathjax_pass0('mins', @_) }
sub do_cmd_mndx { _mathjax_pass0('mndx', @_) }
sub do_cmd_mod { _mathjax_pass1('mod', @_) }
sub do_cmd_ms { _mathjax_pass0('ms', @_) }
sub do_cmd_muTsste { _mathjax_pass0('muTsste', @_) }
sub do_cmd_mumTsste { _mathjax_pass0('mumTsste', @_) }
sub do_cmd_muoTsote { _mathjax_pass0('muoTsote', @_) }
sub do_cmd_muoTsste { _mathjax_pass0('muoTsste', @_) }
sub do_cmd_muoe { _mathjax_pass0('muoe', @_) }
sub do_cmd_muoes { _mathjax_pass0('muoes', @_) }
sub do_cmd_muomTsote { _mathjax_pass0('muomTsote', @_) }
sub do_cmd_muomTsste { _mathjax_pass0('muomTsste', @_) }
sub do_cmd_muooes { _mathjax_pass0('muooes', @_) }
sub do_cmd_muoote { _mathjax_pass0('muoote', @_) }
sub do_cmd_muootesc { _mathjax_pass0('muootesc', @_) }
sub do_cmd_muostep { _mathjax_pass0('muostep', @_) }
sub do_cmd_muote { _mathjax_pass0('muote', @_) }
sub do_cmd_muotesc { _mathjax_pass0('muotesc', @_) }
sub do_cmd_muse { _mathjax_pass0('muse', @_) }
sub do_cmd_muste { _mathjax_pass0('muste', @_) }
sub do_cmd_mustep { _mathjax_pass0('mustep', @_) }
sub do_cmd_mux { _mathjax_pass0('mux', @_) }
sub do_cmd_muxh { _mathjax_pass0('muxh', @_) }
sub do_cmd_mybm { _mathjax_pass0('mybm', @_) }
sub do_cmd_mymod { _mathjax_pass1('mymod', @_) }
sub do_cmd_nacc { _mathjax_pass2('nacc', @_) }
sub do_cmd_nanoamp { _mathjax_pass0('nanoamp', @_) }
sub do_cmd_nanofarad { _mathjax_pass0('nanofarad', @_) }
sub do_cmd_nanosec { _mathjax_pass0('nanosec', @_) }
sub do_cmd_neb { _mathjax_pass0('neb', @_) }
sub do_cmd_newton { _mathjax_pass0('newton', @_) }
sub do_cmd_nn { _mathjax_pass0('nn', @_) }
sub do_cmd_nnr { _mathjax_pass0('nnr', @_) }
sub do_cmd_norm { _mathjax_pass1('norm', @_) }
sub do_cmd_normi { _mathjax_pass1('normi', @_) }
sub do_cmd_normtext { _mathjax_pass1('normtext', @_) }
sub do_cmd_nsixty { _mathjax_pass0('nsixty', @_) }
sub do_cmd_nv { _mathjax_pass0('nv', @_) }
sub do_cmd_nyq { _mathjax_pass0('nyq', @_) }
sub do_cmd_ohm { _mathjax_pass0('ohm', @_) }
sub do_cmd_ok { _mathjax_pass0('ok', @_) }
sub do_cmd_omax { _mathjax_pass0('omax', @_) }
sub do_cmd_on { _mathjax_pass0('on', @_) }
sub do_cmd_onebyfour { _mathjax_passN('onebyfour', 4, @_) }
sub do_cmd_onebyfournts { _mathjax_passN('onebyfournts', 4, @_) }
sub do_cmd_onebythree { _mathjax_passN('onebythree', 3, @_) }
sub do_cmd_onebythreetop { _mathjax_passN('onebythreetop', 3, @_) }
sub do_cmd_onebytwo { _mathjax_pass2('onebytwo', @_) }
sub do_cmd_onebytwotop { _mathjax_pass2('onebytwotop', @_) }
sub do_cmd_onev { _mathjax_pass0('onev', @_) }
sub do_cmd_onevt { _mathjax_pass0('onevt', @_) }
sub do_cmd_oper { _mathjax_pass1('oper', @_) }
sub do_cmd_order { _mathjax_pass1('order', @_) }
sub do_cmd_ov { _mathjax_pass0('ov', @_) }
sub do_cmd_ovn { _mathjax_pass0('ovn', @_) }
sub do_cmd_pb { _mathjax_pass0('pb', @_) }
sub do_cmd_pbm { _mathjax_pass0('pbm', @_) }
sub do_cmd_pbmt { _mathjax_pass0('pbmt', @_) }
sub do_cmd_pbp { _mathjax_pass0('pbp', @_) }
sub do_cmd_pbpt { _mathjax_pass0('pbpt', @_) }
sub do_cmd_pderiv { _mathjax_pass2('pderiv', @_) }
sub do_cmd_pdot { _mathjax_pass0('pdot', @_) }
sub do_cmd_peev { _mathjax_pass0('peev', @_) }
sub do_cmd_pfend { _mathjax_pass0('pfend', @_) }
sub do_cmd_pfendmath { _mathjax_pass0('pfendmath', @_) }
sub do_cmd_picoamp { _mathjax_pass0('picoamp', @_) }
sub do_cmd_picofarad { _mathjax_pass0('picofarad', @_) }
sub do_cmd_picowatt { _mathjax_pass0('picowatt', @_) }
sub do_cmd_pmi { _mathjax_pass0('pmi', @_) }
sub do_cmd_pminus { _mathjax_pass0('pminus', @_) }
sub do_cmd_pole { _mathjax_pass0('pole', @_) }
sub do_cmd_pom { _mathjax_pass0('pom', @_) }
sub do_cmd_pomn { _mathjax_pass0('pomn', @_) }
sub do_cmd_pomns { _mathjax_pass0('pomns', @_) }
sub do_cmd_poms { _mathjax_pass0('poms', @_) }
sub do_cmd_pop { _mathjax_pass0('pop', @_) }
sub do_cmd_poper { _mathjax_pass1('poper', @_) }
sub do_cmd_popn { _mathjax_pass0('popn', @_) }
sub do_cmd_popns { _mathjax_pass0('popns', @_) }
sub do_cmd_pops { _mathjax_pass0('pops', @_) }
sub do_cmd_pp { _mathjax_pass0('pp', @_) }
sub do_cmd_ppi { _mathjax_pass0('ppi', @_) }
sub do_cmd_pplus { _mathjax_pass0('pplus', @_) }
sub do_cmd_pprime { _mathjax_pass0('pprime', @_) }
sub do_cmd_pprimetx { _mathjax_pass0('pprimetx', @_) }
sub do_cmd_projop { _mathjax_pass0('projop', @_) }
sub do_cmd_pt { _mathjax_pass0('pt', @_) }
sub do_cmd_ptilde { _mathjax_pass0('ptilde', @_) }
sub do_cmd_ptt { _mathjax_pass0('ptt', @_) }
sub do_cmd_pv { _mathjax_pass0('pv', @_) }
sub do_cmd_pvec { _mathjax_pass0('pvec', @_) }
sub do_cmd_pvm { _mathjax_pass0('pvm', @_) }
sub do_cmd_pvmt { _mathjax_pass0('pvmt', @_) }
sub do_cmd_pvp { _mathjax_pass0('pvp', @_) }
sub do_cmd_pvpt { _mathjax_pass0('pvpt', @_) }
sub do_cmd_pvt { _mathjax_pass0('pvt', @_) }
sub do_cmd_qb { _mathjax_pass0('qb', @_) }
sub do_cmd_qsp { _mathjax_pass0('qsp', @_) }
sub do_cmd_qv { _mathjax_pass0('qv', @_) }
sub do_cmd_rad { _mathjax_pass0('rad', @_) }
sub do_cmd_rair { _mathjax_pass0('rair', @_) }
sub do_cmd_rb { _mathjax_pass0('rb', @_) }
sub do_cmd_rbr { _mathjax_pass0('rbr', @_) }
sub do_cmd_rc { _mathjax_pass0('rc', @_) }
sub do_cmd_rci { _mathjax_pass0('rci', @_) }
sub do_cmd_rcs { _mathjax_pass0('rcs', @_) }
sub do_cmd_real { _mathjax_pass0('real', @_) }
sub do_cmd_realPart { _mathjax_pass1('realPart', @_) }
sub do_cmd_realPartSq { _mathjax_pass1('realPartSq', @_) }
sub do_cmd_realpart { _mathjax_pass1('realpart', @_) }
sub do_cmd_realparttext { _mathjax_pass1('realparttext', @_) }
sub do_cmd_reals { _mathjax_pass0('reals', @_) }
sub do_cmd_relop { _mathjax_pass1('relop', @_) }
sub do_cmd_rhoejpsi { _mathjax_pass0('rhoejpsi', @_) }
sub do_cmd_rhot { _mathjax_pass0('rhot', @_) }
sub do_cmd_rhotozero { _mathjax_pass0('rhotozero', @_) }
sub do_cmd_rhxn { _mathjax_pass0('rhxn', @_) }
sub do_cmd_ri { _mathjax_pass0('ri', @_) }
sub do_cmd_rms { _mathjax_pass0('rms', @_) }
sub do_cmd_ro { _mathjax_pass0('ro', @_) }
sub do_cmd_rp { _mathjax_pass0('rp', @_) }
sub do_cmd_rpt { _mathjax_pass0('rpt', @_) }
sub do_cmd_rr { _mathjax_pass0('rr', @_) }
sub do_cmd_rt { _mathjax_pass0('rt', @_) }
sub do_cmd_rth { _mathjax_pass0('rth', @_) }
sub do_cmd_rv { _mathjax_pass0('rv', @_) }
sub do_cmd_rz { _mathjax_pass0('rz', @_) }
sub do_cmd_sR { _mathjax_pass0('sR', @_) }
sub do_cmd_sample { _mathjax_pass0('sample', @_) }
sub do_cmd_scale { _mathjax_pass0('scale', @_) }
sub do_cmd_sec { _mathjax_pass0('sec', @_) }
sub do_cmd_seconds { _mathjax_pass0('seconds', @_) }
sub do_cmd_select { _mathjax_pass0('select', @_) }
sub do_cmd_set { _mathjax_pass1('set', @_) }
sub do_cmd_shah { _mathjax_pass0('shah', @_) }
sub do_cmd_shift { _mathjax_pass0('shift', @_) }
sub do_cmd_si { _mathjax_pass0('si', @_) }
sub do_cmd_sigmav { _mathjax_pass0('sigmav', @_) }
sub do_cmd_simpliess { _mathjax_pass0('simpliess', @_) }
sub do_cmd_sinc { _mathjax_pass0('sinc', @_) }
sub do_cmd_sixbyone { _mathjax_passN('sixbyone', 6, @_) }
sub do_cmd_sn { _mathjax_pass0('sn', @_) }
sub do_cmd_str { _mathjax_pass0('str', @_) }
sub do_cmd_tauv { _mathjax_pass0('tauv', @_) }
sub do_cmd_tdelta { _mathjax_pass0('tdelta', @_) }
sub do_cmd_testtilde { _mathjax_pass1('testtilde', @_) }
sub do_cmd_thh { _mathjax_pass0('thh', @_) }
sub do_cmd_threebyone { _mathjax_passN('threebyone', 3, @_) }
sub do_cmd_threebyonenp { _mathjax_passN('threebyonenp', 3, @_) }
sub do_cmd_threebythree { _mathjax_passN('threebythree', 9, @_) }
sub do_cmd_threebythreenp { _mathjax_passN('threebythreenp', 9, @_) }
sub do_cmd_threebythreert { _mathjax_passN('threebythreert', 9, @_) }
sub do_cmd_tminus { _mathjax_pass0('tminus', @_) }
sub do_cmd_tmsq { _mathjax_pass1('tmsq', @_) }
sub do_cmd_tn { _mathjax_pass0('tn', @_) }
sub do_cmd_tplus { _mathjax_pass0('tplus', @_) }
sub do_cmd_tpm { _mathjax_pass0('tpm', @_) }
sub do_cmd_tsixty { _mathjax_pass0('tsixty', @_) }
sub do_cmd_tsw { _mathjax_pass0('tsw', @_) }
sub do_cmd_twobyone { _mathjax_pass2('twobyone', @_) }
sub do_cmd_twobyonenp { _mathjax_pass2('twobyonenp', @_) }
sub do_cmd_twobyonep { _mathjax_pass2('twobyonep', @_) }
sub do_cmd_twobythree { _mathjax_passN('twobythree', 6, @_) }
sub do_cmd_twobythreesp { _mathjax_passN('twobythreesp', 7, @_) }
sub do_cmd_twobytwo { _mathjax_passN('twobytwo', 4, @_) }
sub do_cmd_twobytwonp { _mathjax_passN('twobytwonp', 4, @_) }
sub do_cmd_twobytwonprs { _mathjax_passN('twobytwonprs', 5, @_) }
sub do_cmd_twobytwor { _mathjax_passN('twobytwor', 4, @_) }
sub do_cmd_twobytwors { _mathjax_passN('twobytwors', 5, @_) }
sub do_cmd_tz { _mathjax_pass0('tz', @_) }
sub do_cmd_u { _mathjax_pass0('u', @_) }
sub do_cmd_ub { _mathjax_pass0('ub', @_) }
sub do_cmd_ubar { _mathjax_pass0('ubar', @_) }
sub do_cmd_ubarx { _mathjax_pass0('ubarx', @_) }
sub do_cmd_ubary { _mathjax_pass0('ubary', @_) }
sub do_cmd_ubarz { _mathjax_pass0('ubarz', @_) }
sub do_cmd_um { _mathjax_pass0('um', @_) }
sub do_cmd_umtx { _mathjax_pass0('umtx', @_) }
sub do_cmd_up { _mathjax_pass0('up', @_) }
sub do_cmd_upm { _mathjax_pass0('upm', @_) }
sub do_cmd_ups { _mathjax_pass0('ups', @_) }
sub do_cmd_upsv { _mathjax_pass0('upsv', @_) }
sub do_cmd_us { _mathjax_pass1('us', @_) }
sub do_cmd_ut { _mathjax_pass0('ut', @_) }
sub do_cmd_utt { _mathjax_pass0('utt', @_) }
sub do_cmd_uttt { _mathjax_pass0('uttt', @_) }
sub do_cmd_utttx { _mathjax_pass0('utttx', @_) }
sub do_cmd_uttx { _mathjax_pass0('uttx', @_) }
sub do_cmd_utx { _mathjax_pass0('utx', @_) }
sub do_cmd_uv { _mathjax_pass0('uv', @_) }
sub do_cmd_vb { _mathjax_pass0('vb', @_) }
sub do_cmd_vd { _mathjax_pass0('vd', @_) }
sub do_cmd_vdc { _mathjax_pass0('vdc', @_) }
sub do_cmd_vdelta { _mathjax_pass0('vdelta', @_) }
sub do_cmd_vdp { _mathjax_pass0('vdp', @_) }
sub do_cmd_vh { _mathjax_pass0('vh', @_) }
sub do_cmd_vht { _mathjax_pass0('vht', @_) }
sub do_cmd_vi { _mathjax_pass0('vi', @_) }
sub do_cmd_vin { _mathjax_pass1('vin', @_) }
sub do_cmd_vio { _mathjax_pass0('vio', @_) }
sub do_cmd_vl { _mathjax_pass0('vl', @_) }
sub do_cmd_vls { _mathjax_pass0('vls', @_) }
sub do_cmd_vm { _mathjax_pass0('vm', @_) }
sub do_cmd_vmi { _mathjax_pass0('vmi', @_) }
sub do_cmd_vmls { _mathjax_pass0('vmls', @_) }
sub do_cmd_vmsl { _mathjax_pass0('vmsl', @_) }
sub do_cmd_vn { _mathjax_pass0('vn', @_) }
sub do_cmd_vnm { _mathjax_pass0('vnm', @_) }
sub do_cmd_vnmi { _mathjax_pass0('vnmi', @_) }
sub do_cmd_vnp { _mathjax_pass0('vnp', @_) }
sub do_cmd_vnpi { _mathjax_pass0('vnpi', @_) }
sub do_cmd_vnpm { _mathjax_pass0('vnpm', @_) }
sub do_cmd_volt { _mathjax_pass0('volt', @_) }
sub do_cmd_vp { _mathjax_pass0('vp', @_) }
sub do_cmd_vpi { _mathjax_pass0('vpi', @_) }
sub do_cmd_vpimo { _mathjax_pass0('vpimo', @_) }
sub do_cmd_vpm { _mathjax_pass0('vpm', @_) }
sub do_cmd_vpmi { _mathjax_pass0('vpmi', @_) }
sub do_cmd_vr { _mathjax_pass0('vr', @_) }
sub do_cmd_vro { _mathjax_pass0('vro', @_) }
sub do_cmd_vs { _mathjax_pass0('vs', @_) }
sub do_cmd_vsl { _mathjax_pass0('vsl', @_) }
sub do_cmd_vslm { _mathjax_pass0('vslm', @_) }
sub do_cmd_vslp { _mathjax_pass0('vslp', @_) }
sub do_cmd_vsp { _mathjax_pass0('vsp', @_) }
sub do_cmd_vsr { _mathjax_pass0('vsr', @_) }
sub do_cmd_vsrm { _mathjax_pass0('vsrm', @_) }
sub do_cmd_vsrp { _mathjax_pass0('vsrp', @_) }
sub do_cmd_vt { _mathjax_pass0('vt', @_) }
sub do_cmd_vtilde { _mathjax_pass0('vtilde', @_) }
sub do_cmd_vv { _mathjax_pass0('vv', @_) }
sub do_cmd_vvec { _mathjax_pass0('vvec', @_) }
sub do_cmd_vvecl { _mathjax_pass0('vvecl', @_) }
sub do_cmd_vvecls { _mathjax_pass0('vvecls', @_) }
sub do_cmd_vvecs { _mathjax_pass0('vvecs', @_) }
sub do_cmd_vvecsl { _mathjax_pass0('vvecsl', @_) }
sub do_cmd_vvm { _mathjax_pass0('vvm', @_) }
sub do_cmd_vvp { _mathjax_pass0('vvp', @_) }
sub do_cmd_vvpt { _mathjax_pass0('vvpt', @_) }
sub do_cmd_vvt { _mathjax_pass0('vvt', @_) }
sub do_cmd_vx { _mathjax_pass0('vx', @_) }
sub do_cmd_vxh { _mathjax_pass0('vxh', @_) }
sub do_cmd_watt { _mathjax_pass0('watt', @_) }
sub do_cmd_wh { _mathjax_pass0('wh', @_) }
sub do_cmd_window { _mathjax_pass0('window', @_) }
sub do_cmd_wl { _mathjax_pass0('wl', @_) }
sub do_cmd_wm { _mathjax_pass0('wm', @_) }
sub do_cmd_wmtx { _mathjax_pass0('wmtx', @_) }
sub do_cmd_wn { _mathjax_pass0('wn', @_) }
sub do_cmd_wrap { _mathjax_pass0('wrap', @_) }
sub do_cmd_ws { _mathjax_pass0('ws', @_) }
sub do_cmd_wv { _mathjax_pass0('wv', @_) }
sub do_cmd_wz { _mathjax_pass0('wz', @_) }
sub do_cmd_x { _mathjax_pass0('x', @_) }
sub do_cmd_xK { _mathjax_pass0('xK', @_) }
sub do_cmd_xW { _mathjax_pass0('xW', @_) }
sub do_cmd_xb { _mathjax_pass0('xb', @_) }
sub do_cmd_xddot { _mathjax_pass0('xddot', @_) }
sub do_cmd_xdot { _mathjax_pass0('xdot', @_) }
sub do_cmd_xh { _mathjax_pass0('xh', @_) }
sub do_cmd_xht { _mathjax_pass0('xht', @_) }
sub do_cmd_xhtt { _mathjax_pass0('xhtt', @_) }
sub do_cmd_xhv { _mathjax_pass0('xhv', @_) }
sub do_cmd_xhva { _mathjax_pass0('xhva', @_) }
sub do_cmd_xm { _mathjax_pass0('xm', @_) }
sub do_cmd_xmoc { _mathjax_pass0('xmoc', @_) }
sub do_cmd_xmsc { _mathjax_pass0('xmsc', @_) }
sub do_cmd_xoc { _mathjax_pass0('xoc', @_) }
sub do_cmd_xocsc { _mathjax_pass0('xocsc', @_) }
sub do_cmd_xp { _mathjax_pass0('xp', @_) }
sub do_cmd_xsc { _mathjax_pass0('xsc', @_) }
sub do_cmd_xt { _mathjax_pass0('xt', @_) }
sub do_cmd_xtilde { _mathjax_pass0('xtilde', @_) }
sub do_cmd_xtt { _mathjax_pass0('xtt', @_) }
sub do_cmd_xv { _mathjax_pass0('xv', @_) }
sub do_cmd_xvddot { _mathjax_pass0('xvddot', @_) }
sub do_cmd_xvdot { _mathjax_pass0('xvdot', @_) }
sub do_cmd_xvl { _mathjax_pass0('xvl', @_) }
sub do_cmd_xvls { _mathjax_pass0('xvls', @_) }
sub do_cmd_xvn { _mathjax_pass0('xvn', @_) }
sub do_cmd_xvs { _mathjax_pass0('xvs', @_) }
sub do_cmd_xvsl { _mathjax_pass0('xvsl', @_) }
sub do_cmd_xvt { _mathjax_pass0('xvt', @_) }
sub do_cmd_xz { _mathjax_pass0('xz', @_) }
sub do_cmd_y { _mathjax_pass0('y', @_) }
sub do_cmd_yb { _mathjax_pass0('yb', @_) }
sub do_cmd_yffnm { _mathjax_pass0('yffnm', @_) }
sub do_cmd_yffnmom { _mathjax_pass0('yffnmom', @_) }
sub do_cmd_yfnm { _mathjax_pass0('yfnm', @_) }
sub do_cmd_yfnmmo { _mathjax_pass0('yfnmmo', @_) }
sub do_cmd_yfnmpo { _mathjax_pass0('yfnmpo', @_) }
sub do_cmd_yfull { _mathjax_pass0('yfull', @_) }
sub do_cmd_yh { _mathjax_pass0('yh', @_) }
sub do_cmd_yl { _mathjax_pass0('yl', @_) }
sub do_cmd_ylt { _mathjax_pass0('ylt', @_) }
sub do_cmd_yltt { _mathjax_pass0('yltt', @_) }
sub do_cmd_ylx { _mathjax_pass0('ylx', @_) }
sub do_cmd_ylxx { _mathjax_pass0('ylxx', @_) }
sub do_cmd_ym { _mathjax_pass0('ym', @_) }
sub do_cmd_ymnm { _mathjax_pass0('ymnm', @_) }
sub do_cmd_ymnmmo { _mathjax_pass0('ymnmmo', @_) }
sub do_cmd_ymnmom { _mathjax_pass0('ymnmom', @_) }
sub do_cmd_ymnmpfi { _mathjax_pass0('ymnmpfi', @_) }
sub do_cmd_ymnmpo { _mathjax_pass0('ymnmpo', @_) }
sub do_cmd_ymnmpth { _mathjax_pass0('ymnmpth', @_) }
sub do_cmd_ymnpom { _mathjax_pass0('ymnpom', @_) }
sub do_cmd_ymt { _mathjax_pass0('ymt', @_) }
sub do_cmd_ymx { _mathjax_pass0('ymx', @_) }
sub do_cmd_ynm { _mathjax_pass0('ynm', @_) }
sub do_cmd_ynmmo { _mathjax_pass0('ynmmo', @_) }
sub do_cmd_ynmom { _mathjax_pass0('ynmom', @_) }
sub do_cmd_ynmompf { _mathjax_pass0('ynmompf', @_) }
sub do_cmd_ynmompt { _mathjax_pass0('ynmompt', @_) }
sub do_cmd_ynmpfi { _mathjax_pass0('ynmpfi', @_) }
sub do_cmd_ynmpo { _mathjax_pass0('ynmpo', @_) }
sub do_cmd_ynmpth { _mathjax_pass0('ynmpth', @_) }
sub do_cmd_ynpom { _mathjax_pass0('ynpom', @_) }
sub do_cmd_ynpompo { _mathjax_pass0('ynpompo', @_) }
sub do_cmd_yp { _mathjax_pass0('yp', @_) }
sub do_cmd_ypm { _mathjax_pass0('ypm', @_) }
sub do_cmd_ypmt { _mathjax_pass0('ypmt', @_) }
sub do_cmd_ypmtt { _mathjax_pass0('ypmtt', @_) }
sub do_cmd_ypmx { _mathjax_pass0('ypmx', @_) }
sub do_cmd_ypmxx { _mathjax_pass0('ypmxx', @_) }
sub do_cmd_ypnm { _mathjax_pass0('ypnm', @_) }
sub do_cmd_ypnmmo { _mathjax_pass0('ypnmmo', @_) }
sub do_cmd_ypnmom { _mathjax_pass0('ypnmom', @_) }
sub do_cmd_ypnmpfi { _mathjax_pass0('ypnmpfi', @_) }
sub do_cmd_ypnmpo { _mathjax_pass0('ypnmpo', @_) }
sub do_cmd_ypnmpth { _mathjax_pass0('ypnmpth', @_) }
sub do_cmd_ypnpom { _mathjax_pass0('ypnpom', @_) }
sub do_cmd_ypt { _mathjax_pass0('ypt', @_) }
sub do_cmd_ypx { _mathjax_pass0('ypx', @_) }
sub do_cmd_yr { _mathjax_pass0('yr', @_) }
sub do_cmd_yrt { _mathjax_pass0('yrt', @_) }
sub do_cmd_yrtt { _mathjax_pass0('yrtt', @_) }
sub do_cmd_yrttt { _mathjax_pass0('yrttt', @_) }
sub do_cmd_yrttttt { _mathjax_pass0('yrttttt', @_) }
sub do_cmd_yrx { _mathjax_pass0('yrx', @_) }
sub do_cmd_yrxx { _mathjax_pass0('yrxx', @_) }
sub do_cmd_yt { _mathjax_pass0('yt', @_) }
sub do_cmd_ytt { _mathjax_pass0('ytt', @_) }
sub do_cmd_yttt { _mathjax_pass0('yttt', @_) }
sub do_cmd_yttttt { _mathjax_pass0('yttttt', @_) }
sub do_cmd_yttx { _mathjax_pass0('yttx', @_) }
sub do_cmd_yv { _mathjax_pass0('yv', @_) }
sub do_cmd_yvec { _mathjax_pass0('yvec', @_) }
sub do_cmd_yx { _mathjax_pass0('yx', @_) }
sub do_cmd_yxx { _mathjax_pass0('yxx', @_) }
sub do_cmd_yxxt { _mathjax_pass0('yxxt', @_) }
sub do_cmd_yxxxx { _mathjax_pass0('yxxxx', @_) }
sub do_cmd_zbox { _mathjax_pass1('zbox', @_) }
sub do_cmd_zboxlt { _mathjax_pass1('zboxlt', @_) }
sub do_cmd_zeev { _mathjax_pass0('zeev', @_) }
sub do_cmd_zero { _mathjax_pass0('zero', @_) }
sub do_cmd_zeropad { _mathjax_pass0('zeropad', @_) }
sub do_cmd_zerov { _mathjax_pass0('zerov', @_) }
sub do_cmd_zi { _mathjax_pass0('zi', @_) }
sub do_cmd_zio { _mathjax_pass0('zio', @_) }
sub do_cmd_zmn { _mathjax_pass0('zmn', @_) }
sub do_cmd_zmoh { _mathjax_pass0('zmoh', @_) }
sub do_cmd_zmt { _mathjax_pass0('zmt', @_) }
sub do_cmd_zoh { _mathjax_pass0('zoh', @_) }
sub do_cmd_zp { _mathjax_pass0('zp', @_) }
sub do_cmd_zv { _mathjax_pass0('zv', @_) }
sub do_cmd_zvec { _mathjax_pass0('zvec', @_) }
sub do_cmd_zvv { _mathjax_pass0('zvv', @_) }

1;
